/* 문장별 예시 대화 — 키: "<situationId>|<groupIndex>|<exampleIndex>"
 * 각 줄: { s:"A"|"B", en(=스페인어), ko, hl?:true }
 * 알파벳/숫자나열 등 대화가 어색한 항목은 제외 → 그런 문장엔 💬 버튼이 안 보임
 */
window.DIALOGS = {
  /* ===== 기초(문장형) ===== */
  "numeros|3|0": [ {s:"A",en:"¿Cuánto cuesta?",ko:"얼마예요?",hl:true}, {s:"B",en:"Diez euros.",ko:"10유로예요."} ],
  "numeros|3|1": [ {s:"A",en:"¿Cuánto es?",ko:"얼마예요?"}, {s:"B",en:"Son diez euros.",ko:"10유로예요.",hl:true} ],
  "numeros|3|2": [ {s:"A",en:"¿Cuántos años tienes?",ko:"몇 살이에요?"}, {s:"B",en:"Tengo veinticinco años.",ko:"저는 25살이에요.",hl:true} ],
  "numeros|3|3": [ {s:"A",en:"¿Cuál es tu teléfono?",ko:"전화번호가 뭐예요?"}, {s:"B",en:"Mi número es seis, dos, tres...",ko:"제 번호는 6, 2, 3…이에요.",hl:true} ],
  "numeros|3|4": [ {s:"A",en:"¿Cuánto subió el precio?",ko:"가격이 얼마나 올랐어요?"}, {s:"B",en:"El dos por ciento.",ko:"2 퍼센트요.",hl:true} ],
  "hora|0|0": [ {s:"A",en:"¿Qué hora es?",ko:"몇 시예요?",hl:true}, {s:"B",en:"Son las tres.",ko:"3시예요."} ],
  "hora|0|1": [ {s:"A",en:"¿Ya es la una?",ko:"벌써 1시예요?"}, {s:"B",en:"Es la una.",ko:"1시예요.",hl:true} ],
  "hora|0|2": [ {s:"A",en:"¿A qué hora llegas?",ko:"몇 시에 도착해?"}, {s:"B",en:"Son las dos y media.",ko:"2시 반이에요.",hl:true} ],
  "hora|0|3": [ {s:"A",en:"¿Tienes hora?",ko:"몇 시인지 아세요?"}, {s:"B",en:"Son las tres y cuarto.",ko:"3시 15분이에요.",hl:true} ],
  "hora|0|4": [ {s:"A",en:"¿Llegamos tarde?",ko:"우리 늦었어?"}, {s:"B",en:"Son las cinco menos cuarto.",ko:"5시 15분 전(4시 45분)이에요.",hl:true} ],
  "hora|1|0": [ {s:"A",en:"¿Cuándo empieza?",ko:"언제 시작해?"}, {s:"B",en:"A las ocho de la mañana.",ko:"오전 8시에요.",hl:true} ],
  "hora|1|1": [ {s:"A",en:"¿Cuándo nos vemos?",ko:"언제 볼까?"}, {s:"B",en:"A las tres de la tarde.",ko:"오후 3시에요.",hl:true} ],
  "hora|1|2": [ {s:"A",en:"¿A qué hora es la cena?",ko:"저녁 몇 시예요?"}, {s:"B",en:"A las diez de la noche.",ko:"밤 10시에요.",hl:true} ],
  "hora|1|3": [ {s:"A",en:"¿Cuándo comemos?",ko:"언제 먹어요?"}, {s:"B",en:"Al mediodía.",ko:"정오에요.",hl:true} ],
  "hora|1|4": [ {s:"A",en:"¿Cuándo termina la fiesta?",ko:"파티 언제 끝나?"}, {s:"B",en:"A medianoche.",ko:"자정에요.",hl:true} ],
  "hora|2|0": [ {s:"A",en:"¿Qué día es hoy?",ko:"오늘 무슨 요일이에요?",hl:true}, {s:"B",en:"Hoy es martes.",ko:"오늘은 화요일이에요."} ],
  "hora|2|1": [ {s:"A",en:"¿Hoy es lunes?",ko:"오늘 월요일이에요?"}, {s:"B",en:"Hoy es lunes.",ko:"오늘은 월요일이에요.",hl:true} ],
  "hora|2|2": [ {s:"A",en:"¿Sabes la fecha?",ko:"날짜 알아요?"}, {s:"B",en:"¿Cuál es la fecha de hoy?",ko:"오늘 며칠이에요?",hl:true} ],
  "hora|2|3": [ {s:"A",en:"¿A cuántos estamos?",ko:"며칠이에요?"}, {s:"B",en:"Hoy es seis de junio.",ko:"오늘은 6월 6일이에요.",hl:true} ],
  "hora|2|4": [ {s:"A",en:"¿Cuándo es tu cumpleaños?",ko:"생일 언제예요?"}, {s:"B",en:"Mi cumpleaños es en mayo.",ko:"제 생일은 5월이에요.",hl:true} ],
  "colores|0|4": [ {s:"A",en:"¿Qué color prefieres?",ko:"무슨 색이 좋아요?"}, {s:"B",en:"Me gusta el color azul.",ko:"저는 파란색을 좋아해요.",hl:true} ],
  "colores|1|0": [ {s:"A",en:"¿Es grande o pequeño?",ko:"큰 거야 작은 거야?",hl:true}, {s:"B",en:"Es grande.",ko:"커."} ],
  "colores|2|4": [ {s:"A",en:"¿Te gusta la comida?",ko:"음식 맛있어?"}, {s:"B",en:"La comida está buena.",ko:"음식이 맛있어요.",hl:true} ],
  "preguntas|1|0": [ {s:"A",en:"¿Qué es esto?",ko:"이게 뭐예요?",hl:true}, {s:"B",en:"Es un regalo para ti.",ko:"널 위한 선물이야."} ],
  "preguntas|1|1": [ {s:"A",en:"¿Dónde está el baño?",ko:"화장실이 어디예요?",hl:true}, {s:"B",en:"Al fondo, a la derecha.",ko:"안쪽 오른쪽이에요."} ],
  "preguntas|1|2": [ {s:"A",en:"¿Cuándo llegas?",ko:"언제 도착해?",hl:true}, {s:"B",en:"En diez minutos.",ko:"10분 뒤에."} ],
  "preguntas|1|3": [ {s:"A",en:"¿Cómo te llamas?",ko:"이름이 뭐예요?",hl:true}, {s:"B",en:"Me llamo Jun.",ko:"저는 준이에요."} ],
  "preguntas|1|4": [ {s:"A",en:"¿Por qué no vienes?",ko:"왜 안 와?",hl:true}, {s:"B",en:"Porque estoy cansado.",ko:"피곤해서."} ],
  "verbos|0|4": [ {s:"A",en:"¿Eres estudiante?",ko:"학생이에요?"}, {s:"B",en:"Soy estudiante.",ko:"저는 학생이에요.",hl:true} ],
  "verbos|1|3": [ {s:"A",en:"¿Cómo te sientes?",ko:"기분 어때?"}, {s:"B",en:"Estoy cansado.",ko:"저 피곤해요.",hl:true} ],
  "verbos|1|4": [ {s:"A",en:"¿Dónde estás?",ko:"너 어디야?",hl:true}, {s:"B",en:"Estoy en casa.",ko:"집에 있어."} ],
  "verbos|2|2": [ {s:"A",en:"¿Quieres comer algo?",ko:"뭐 먹을래?"}, {s:"B",en:"Tengo hambre.",ko:"배고파요.",hl:true} ],
  "verbos|2|4": [ {s:"A",en:"¿Tienes tiempo?",ko:"시간 있어?",hl:true}, {s:"B",en:"Sí, ¿qué pasa?",ko:"응, 무슨 일이야?"} ],
  "verbos|3|2": [ {s:"A",en:"¿Adónde vas?",ko:"어디 가?"}, {s:"B",en:"Voy a casa.",ko:"집에 가.",hl:true} ],
  "verbos|3|4": [ {s:"A",en:"¿Adónde vas?",ko:"어디 가?",hl:true}, {s:"B",en:"Voy al trabajo.",ko:"일하러 가."} ],
  "supervivencia|0|0": [ {s:"A",en:"¿Quieres más?",ko:"더 줄까?"}, {s:"B",en:"Sí. / No.",ko:"네. / 아니요.",hl:true} ],
  "supervivencia|0|1": [ {s:"A",en:"¿Te ayudo?",ko:"도와줄까?"}, {s:"B",en:"Por favor.",ko:"부탁해요.",hl:true} ],
  "supervivencia|0|2": [ {s:"A",en:"Aquí tienes.",ko:"여기요."}, {s:"B",en:"Gracias. / Muchas gracias.",ko:"고마워요. / 정말 고마워요.",hl:true} ],
  "supervivencia|0|3": [ {s:"A",en:"Muchas gracias.",ko:"정말 고마워요."}, {s:"B",en:"De nada.",ko:"천만에요.",hl:true} ],
  "supervivencia|0|4": [ {s:"A",en:"Perdón. / Disculpe.",ko:"죄송해요. / 실례합니다.",hl:true}, {s:"B",en:"No pasa nada.",ko:"괜찮아요."} ],
  "supervivencia|1|0": [ {s:"A",en:"¿Lo entiendes?",ko:"이해돼?"}, {s:"B",en:"No entiendo.",ko:"이해 못 했어요.",hl:true} ],
  "supervivencia|1|1": [ {s:"A",en:"...y eso es todo.",ko:"…그게 다예요."}, {s:"B",en:"¿Puede repetir, por favor?",ko:"다시 말해 주시겠어요?",hl:true} ],
  "supervivencia|1|2": [ {s:"A",en:"Hablo muy rápido, ¿no?",ko:"제가 너무 빠르죠?"}, {s:"B",en:"Más despacio, por favor.",ko:"조금 천천히 말해 주세요.",hl:true} ],
  "supervivencia|1|3": [ {s:"A",en:"¿Hablas español?",ko:"스페인어 해요?"}, {s:"B",en:"No hablo español muy bien.",ko:"스페인어를 잘 못해요.",hl:true} ],
  "supervivencia|1|4": [ {s:"A",en:"No entiendo coreano.",ko:"한국어를 못해요."}, {s:"B",en:"¿Habla inglés?",ko:"영어 하세요?",hl:true} ],
  "supervivencia|2|0": [ {s:"A",en:"¿Cómo se dice esto en español?",ko:"이거 스페인어로 어떻게 말해요?",hl:true}, {s:"B",en:"Se dice \"libro\".",ko:"'libro'라고 해요."} ],
  "supervivencia|2|1": [ {s:"A",en:"¿Qué significa esto?",ko:"이게 무슨 뜻이에요?",hl:true}, {s:"B",en:"Significa \"casa\".",ko:"'집'이라는 뜻이에요."} ],
  "supervivencia|2|2": [ {s:"A",en:"¿Cómo se escribe?",ko:"어떻게 쓰나요?",hl:true}, {s:"B",en:"L-I-B-R-O.",ko:"L-I-B-R-O요."} ],

  /* ===== 회화 ===== */
  "saludos|0|0": [ {s:"A",en:"¡Hola! ¿Qué tal?",ko:"안녕! 어떻게 지내?",hl:true}, {s:"B",en:"¡Bien! ¿Y tú?",ko:"좋아! 너는?"} ],
  "saludos|0|1": [ {s:"A",en:"¿Cómo estás hoy?",ko:"오늘 어떻게 지내?",hl:true}, {s:"B",en:"Muy bien, gracias.",ko:"아주 좋아, 고마워."} ],
  "saludos|0|2": [ {s:"A",en:"¿Cómo estás?",ko:"어떻게 지내?"}, {s:"B",en:"Muy bien, gracias. ¿Y tú?",ko:"아주 좋아, 고마워. 너는?",hl:true} ],
  "saludos|0|3": [ {s:"A",en:"¿Todo bien?",ko:"다 괜찮아?"}, {s:"B",en:"Aquí, todo tranquilo.",ko:"응, 다 평온해.",hl:true} ],
  "saludos|0|4": [ {s:"A",en:"¿Cómo va todo?",ko:"다 어떻게 돼가?"}, {s:"B",en:"Más o menos.",ko:"그럭저럭이야.",hl:true} ],
  "saludos|1|0": [ {s:"A",en:"Buenos días, ¿cómo amaneció?",ko:"좋은 아침이에요, 잘 주무셨어요?",hl:true}, {s:"B",en:"Muy bien, gracias.",ko:"아주 잘 잤어요, 고마워요."} ],
  "saludos|1|1": [ {s:"A",en:"Buenas tardes a todos.",ko:"모두 좋은 오후예요.",hl:true}, {s:"B",en:"Buenas tardes.",ko:"좋은 오후예요."} ],
  "saludos|1|2": [ {s:"A",en:"Me voy a dormir.",ko:"자러 갈게."}, {s:"B",en:"Buenas noches, que descanses.",ko:"잘 자, 푹 쉬어.",hl:true} ],
  "saludos|1|3": [ {s:"A",en:"¡Buenas! ¿Qué cuentas?",ko:"안녕! 뭐 새로운 거 있어?",hl:true}, {s:"B",en:"Nada nuevo, ¿y tú?",ko:"별거 없어, 너는?"} ],
  "saludos|1|4": [ {s:"A",en:"Que tengas un buen día.",ko:"좋은 하루 보내요."}, {s:"B",en:"Igualmente, gracias.",ko:"당신도요, 감사해요.",hl:true} ],
  "saludos|2|0": [ {s:"A",en:"¡Cuánto tiempo sin verte!",ko:"정말 오랜만이다!",hl:true}, {s:"B",en:"¡Es verdad! Me alegro de verte.",ko:"그러게! 보니까 반갑다."} ],
  "saludos|2|1": [ {s:"A",en:"¡Qué alegría verte!",ko:"보니까 너무 반갑다!",hl:true}, {s:"B",en:"¡Lo mismo digo!",ko:"나도 그래!"} ],
  "saludos|2|2": [ {s:"A",en:"¿Cómo te ha ido?",ko:"그동안 어떻게 지냈어?",hl:true}, {s:"B",en:"Muy bien, ocupado pero feliz.",ko:"잘 지냈어, 바빴지만 좋았어."} ],
  "saludos|2|3": [ {s:"A",en:"Tenemos que vernos pronto.",ko:"우리 조만간 만나야 해.",hl:true}, {s:"B",en:"¡Sí! ¿Este fin de semana?",ko:"응! 이번 주말 어때?"} ],
  "saludos|2|4": [ {s:"A",en:"A ver si quedamos un día.",ko:"언제 한번 보자.",hl:true}, {s:"B",en:"Me parece genial.",ko:"좋아."} ],
  "saludos|3|0": [ {s:"A",en:"¡Qué calor hace hoy!",ko:"오늘 진짜 덥다!",hl:true}, {s:"B",en:"Sí, es horrible.",ko:"응, 정말 끔찍해."} ],
  "saludos|3|1": [ {s:"A",en:"Hace mucho frío, ¿verdad?",ko:"엄청 춥지, 그치?",hl:true}, {s:"B",en:"Sí, traje abrigo.",ko:"응, 외투 가져왔어."} ],
  "saludos|3|2": [ {s:"A",en:"Parece que va a llover.",ko:"비 올 것 같아.",hl:true}, {s:"B",en:"Mejor llevo paraguas.",ko:"우산 챙기는 게 낫겠다."} ],
  "saludos|3|3": [ {s:"A",en:"Hace un día precioso.",ko:"날씨 정말 좋다.",hl:true}, {s:"B",en:"Perfecto para pasear.",ko:"산책하기 딱이야."} ],
  "saludos|3|4": [ {s:"A",en:"Lleva días lloviendo.",ko:"며칠째 비가 와."}, {s:"B",en:"Espero que mejore el tiempo.",ko:"날씨가 좋아지면 좋겠어.",hl:true} ],
  "saludos|4|0": [ {s:"A",en:"Me voy. ¡Hasta luego!",ko:"나 갈게. 이따 봐!",hl:true}, {s:"B",en:"¡Adiós! Cuídate.",ko:"잘 가! 몸조심해."} ],
  "saludos|4|1": [ {s:"A",en:"¡Nos vemos pronto!",ko:"곧 또 봐!",hl:true}, {s:"B",en:"¡Hasta pronto!",ko:"곧 봐!"} ],
  "saludos|4|2": [ {s:"A",en:"¡Cuídate mucho!",ko:"몸조심해!",hl:true}, {s:"B",en:"¡Tú también!",ko:"너도!"} ],
  "saludos|4|3": [ {s:"A",en:"¡Que tengas un buen día!",ko:"좋은 하루 보내!",hl:true}, {s:"B",en:"¡Gracias, igualmente!",ko:"고마워, 너도!"} ],
  "saludos|4|4": [ {s:"A",en:"Me alegro de verte.",ko:"만나서 반가웠어.",hl:true}, {s:"B",en:"Yo también. ¡Hasta la próxima!",ko:"나도. 다음에 봐!"} ],
  "presentarse|0|0": [ {s:"A",en:"Hola, me llamo Jun. Mucho gusto.",ko:"안녕하세요, 저는 준이에요. 반가워요.",hl:true}, {s:"B",en:"Encantada, soy Sara.",ko:"반가워요, 저는 사라예요."} ],
  "presentarse|0|1": [ {s:"A",en:"Soy Jun.",ko:"저는 준이에요."}, {s:"B",en:"Encantado de conocerte.",ko:"만나서 반가워요.",hl:true} ],
  "presentarse|0|2": [ {s:"A",en:"Hola, ¿cómo estás?",ko:"안녕하세요?"}, {s:"B",en:"Encantada, soy Sara.",ko:"반가워요, 저는 사라예요.",hl:true} ],
  "presentarse|0|3": [ {s:"A",en:"Gracias por venir.",ko:"와줘서 고마워요."}, {s:"B",en:"El gusto es mío.",ko:"저야말로 반가워요.",hl:true} ],
  "presentarse|0|4": [ {s:"A",en:"¿Cómo te llamas?",ko:"이름이 뭐예요?",hl:true}, {s:"B",en:"Me llamo Jun.",ko:"저는 준이에요."} ],
  "presentarse|1|0": [ {s:"A",en:"¿A qué te dedicas?",ko:"무슨 일 하세요?",hl:true}, {s:"B",en:"Soy profesor. ¿Y tú?",ko:"교사예요. 당신은요?"} ],
  "presentarse|1|1": [ {s:"A",en:"¿En qué trabajas?",ko:"어떤 일 하세요?"}, {s:"B",en:"Trabajo en marketing.",ko:"마케팅 일을 해요.",hl:true} ],
  "presentarse|1|2": [ {s:"A",en:"¿Cuál es tu profesión?",ko:"직업이 뭐예요?"}, {s:"B",en:"Soy desarrollador de software.",ko:"저는 소프트웨어 개발자예요.",hl:true} ],
  "presentarse|1|3": [ {s:"A",en:"¿Dónde trabajas?",ko:"어디서 일해요?"}, {s:"B",en:"Trabajo en una empresa pequeña.",ko:"작은 회사에서 일해요.",hl:true} ],
  "presentarse|1|4": [ {s:"A",en:"¿Estás trabajando ahora?",ko:"지금 일해요?"}, {s:"B",en:"Ahora estoy buscando trabajo.",ko:"지금은 일자리를 찾고 있어요.",hl:true} ],
  "presentarse|2|0": [ {s:"A",en:"¿De dónde eres?",ko:"어디서 왔어요?",hl:true}, {s:"B",en:"Soy de Corea. ¿Y tú?",ko:"한국에서 왔어요. 당신은요?"} ],
  "presentarse|2|1": [ {s:"A",en:"¿De qué ciudad eres?",ko:"어느 도시 출신이에요?"}, {s:"B",en:"Soy de Seúl, Corea del Sur.",ko:"저는 한국 서울에서 왔어요.",hl:true} ],
  "presentarse|2|2": [ {s:"A",en:"¿Vives en Corea?",ko:"한국에 살아요?"}, {s:"B",en:"Soy coreano, pero vivo aquí.",ko:"저는 한국인인데 여기 살아요.",hl:true} ],
  "presentarse|2|3": [ {s:"A",en:"¿Has estado en Corea?",ko:"한국에 가본 적 있어요?",hl:true}, {s:"B",en:"Todavía no, pero quiero ir.",ko:"아직요, 근데 가보고 싶어요."} ],
  "presentarse|2|4": [ {s:"A",en:"¿Cuánto tiempo llevas aquí?",ko:"여기 산 지 얼마나 됐어요?",hl:true}, {s:"B",en:"Unos tres años.",ko:"3년 정도요."} ],
  "presentarse|3|0": [ {s:"A",en:"¿Qué te gusta hacer en tu tiempo libre?",ko:"여가 시간에 뭐 해요?",hl:true}, {s:"B",en:"Toco la guitarra.",ko:"기타를 쳐요."} ],
  "presentarse|3|1": [ {s:"A",en:"¿Tienes algún hobby?",ko:"취미 있어요?"}, {s:"B",en:"Me encanta el senderismo.",ko:"등산을 정말 좋아해요.",hl:true} ],
  "presentarse|3|2": [ {s:"A",en:"¿Qué haces los fines de semana?",ko:"주말엔 뭐 해요?"}, {s:"B",en:"Me gusta probar restaurantes nuevos.",ko:"새 식당 가보는 걸 좋아해요.",hl:true} ],
  "presentarse|3|3": [ {s:"A",en:"¿Sales mucho?",ko:"외출 많이 해요?"}, {s:"B",en:"Los fines de semana descanso en casa.",ko:"주말엔 집에서 쉬어요.",hl:true} ],
  "presentarse|3|4": [ {s:"A",en:"A mí también me gusta el senderismo.",ko:"저도 등산 좋아해요."}, {s:"B",en:"¡Tenemos mucho en común!",ko:"우리 통하는 게 많네요!",hl:true} ],
  "presentarse|4|0": [ {s:"A",en:"Mantengámonos en contacto.",ko:"연락하고 지내요.",hl:true}, {s:"B",en:"¡Claro!",ko:"좋아요!"} ],
  "presentarse|4|1": [ {s:"A",en:"¿Me das tu número?",ko:"번호 받을 수 있을까요?",hl:true}, {s:"B",en:"Sí, te lo apunto.",ko:"네, 적어드릴게요."} ],
  "presentarse|4|2": [ {s:"A",en:"¿Tienes Instagram?",ko:"인스타 하세요?",hl:true}, {s:"B",en:"Sí, te sigo.",ko:"네, 팔로우할게요."} ],
  "presentarse|4|3": [ {s:"A",en:"¿Cuándo era el evento?",ko:"행사 언제였죠?"}, {s:"B",en:"Te escribo luego.",ko:"나중에 연락할게요.",hl:true} ],
  "presentarse|4|4": [ {s:"A",en:"Tengo que irme.",ko:"이만 가봐야겠어요."}, {s:"B",en:"Me encantó hablar contigo.",ko:"얘기 나눠서 정말 좋았어요.",hl:true} ],
  "restaurante|0|0": [ {s:"A",en:"¿Me pone un café con leche, por favor?",ko:"카페라떼 한 잔 주시겠어요?",hl:true}, {s:"B",en:"Claro, ¿algo más?",ko:"네, 더 필요한 거 있으세요?"} ],
  "restaurante|0|1": [ {s:"A",en:"¿Ya saben qué pedir?",ko:"주문 정하셨어요?"}, {s:"B",en:"Para mí, la paella.",ko:"저는 빠에야로 할게요.",hl:true} ],
  "restaurante|0|2": [ {s:"A",en:"¿Para llevar, por favor?",ko:"포장되나요?",hl:true}, {s:"B",en:"Sí, ahora se lo preparo.",ko:"네, 바로 준비해 드릴게요."} ],
  "restaurante|0|3": [ {s:"A",en:"Yo quiero la sopa.",ko:"저는 수프로 할게요."}, {s:"B",en:"Yo quiero lo mismo.",ko:"저도 같은 걸로요.",hl:true} ],
  "restaurante|0|4": [ {s:"A",en:"¿Nos trae agua, por favor?",ko:"물 좀 주시겠어요?",hl:true}, {s:"B",en:"Enseguida.",ko:"바로 드릴게요."} ],
  "restaurante|1|0": [ {s:"A",en:"¿Qué me recomienda?",ko:"뭘 추천하시나요?",hl:true}, {s:"B",en:"La paella está muy buena.",ko:"빠에야가 아주 맛있어요."} ],
  "restaurante|1|1": [ {s:"A",en:"¿Cuál es la especialidad de la casa?",ko:"이 집 대표 메뉴가 뭐예요?",hl:true}, {s:"B",en:"El pulpo a la gallega.",ko:"갈리시아식 문어요."} ],
  "restaurante|1|2": [ {s:"A",en:"¿La pasta está buena aquí?",ko:"여기 파스타 맛있어요?",hl:true}, {s:"B",en:"Es de lo mejor que tenemos.",ko:"저희 메뉴 중 최고예요."} ],
  "restaurante|1|3": [ {s:"A",en:"¿Qué lleva este plato?",ko:"이 음식엔 뭐가 들어가요?",hl:true}, {s:"B",en:"Pollo, verduras y arroz.",ko:"닭고기, 채소, 밥이요."} ],
  "restaurante|1|4": [ {s:"A",en:"¿Es muy picante?",ko:"많이 매워요?",hl:true}, {s:"B",en:"Solo un poco.",ko:"조금만요."} ],
  "restaurante|2|0": [ {s:"A",en:"¿Tienen mesa para dos?",ko:"두 명 자리 있나요?",hl:true}, {s:"B",en:"Sí, síganme.",ko:"네, 따라오세요."} ],
  "restaurante|2|1": [ {s:"A",en:"¿Tienen reserva?",ko:"예약하셨나요?"}, {s:"B",en:"Tengo una reserva a nombre de Kim.",ko:"Kim 이름으로 예약했어요.",hl:true} ],
  "restaurante|2|2": [ {s:"A",en:"¿Cuánto hay que esperar?",ko:"얼마나 기다려야 하나요?",hl:true}, {s:"B",en:"Unos quince minutos.",ko:"15분 정도요."} ],
  "restaurante|2|3": [ {s:"A",en:"¿Podemos sentarnos junto a la ventana?",ko:"창가에 앉을 수 있을까요?",hl:true}, {s:"B",en:"Claro, por aquí.",ko:"그럼요, 이쪽으로요."} ],
  "restaurante|2|4": [ {s:"A",en:"¿Se puede comer en la terraza?",ko:"테라스에서 먹을 수 있나요?",hl:true}, {s:"B",en:"Sí, está abierta.",ko:"네, 열려 있어요."} ],
  "restaurante|3|0": [ {s:"A",en:"Perdone, ¿nos trae la carta otra vez?",ko:"저기요, 메뉴 다시 주시겠어요?",hl:true}, {s:"B",en:"Por supuesto.",ko:"그럼요."} ],
  "restaurante|3|1": [ {s:"A",en:"¿Me trae unas servilletas?",ko:"냅킨 좀 주시겠어요?",hl:true}, {s:"B",en:"Ahora mismo.",ko:"바로요."} ],
  "restaurante|3|2": [ {s:"A",en:"Creo que esto no es lo que pedí.",ko:"이건 제가 주문한 게 아닌 것 같아요.",hl:true}, {s:"B",en:"Disculpe, lo reviso.",ko:"죄송합니다, 확인할게요."} ],
  "restaurante|3|3": [ {s:"A",en:"Esto está un poco frío.",ko:"이거 좀 식었어요.",hl:true}, {s:"B",en:"Lo siento, lo caliento.",ko:"죄송해요, 데워드릴게요."} ],
  "restaurante|3|4": [ {s:"A",en:"¿Me lo puede calentar un poco?",ko:"이거 좀 데워주실 수 있나요?",hl:true}, {s:"B",en:"Claro, un momento.",ko:"그럼요, 잠시만요."} ],
  "restaurante|4|0": [ {s:"A",en:"La cuenta, por favor.",ko:"계산서 주세요.",hl:true}, {s:"B",en:"Enseguida se la traigo.",ko:"바로 가져다드릴게요."} ],
  "restaurante|4|1": [ {s:"A",en:"¿Aceptan tarjeta?",ko:"카드 되나요?",hl:true}, {s:"B",en:"Sí, sin problema.",ko:"네, 문제없어요."} ],
  "restaurante|4|2": [ {s:"A",en:"¿Podemos pagar por separado?",ko:"따로 계산할 수 있나요?",hl:true}, {s:"B",en:"Claro, ¿cómo lo dividimos?",ko:"그럼요, 어떻게 나눌까요?"} ],
  "restaurante|4|3": [ {s:"A",en:"¿Cuánto te debo?",ko:"나 얼마 내면 돼?"}, {s:"B",en:"Esta vez invito yo.",ko:"이번엔 내가 살게.",hl:true} ],
  "restaurante|4|4": [ {s:"A",en:"Aquí tiene. Quédese con el cambio.",ko:"여기요. 잔돈은 가지세요.",hl:true}, {s:"B",en:"¡Muchas gracias!",ko:"정말 감사합니다!"} ],
  "compras|0|0": [ {s:"A",en:"¿Tiene esto en talla mediana?",ko:"이거 M 사이즈로 있나요?",hl:true}, {s:"B",en:"Voy a mirar.",ko:"확인해 볼게요."} ],
  "compras|0|1": [ {s:"A",en:"¿Lo tiene en negro?",ko:"이거 검정색으로 있나요?",hl:true}, {s:"B",en:"Sí, aquí está.",ko:"네, 여기 있어요."} ],
  "compras|0|2": [ {s:"A",en:"¿Tiene una talla más pequeña?",ko:"더 작은 사이즈 있나요?",hl:true}, {s:"B",en:"Tenemos la pequeña.",ko:"S 사이즈 있어요."} ],
  "compras|0|3": [ {s:"A",en:"¿Este es el único color?",ko:"색상은 이거뿐인가요?",hl:true}, {s:"B",en:"También lo hay en azul.",ko:"파란색도 있어요."} ],
  "compras|0|4": [ {s:"A",en:"¿Me lo puedo probar?",ko:"입어봐도 될까요?",hl:true}, {s:"B",en:"Sí, el probador está allí.",ko:"네, 탈의실은 저쪽이에요."} ],
  "compras|1|0": [ {s:"A",en:"¿Le ayudo en algo?",ko:"뭐 도와드릴까요?"}, {s:"B",en:"Solo estoy mirando, gracias.",ko:"그냥 구경하는 거예요, 감사해요.",hl:true} ],
  "compras|1|1": [ {s:"A",en:"¿Busca algo?",ko:"뭐 찾으세요?"}, {s:"B",en:"Estoy echando un vistazo.",ko:"그냥 둘러보고 있어요.",hl:true} ],
  "compras|1|2": [ {s:"A",en:"Avíseme si necesita ayuda.",ko:"도움 필요하면 말씀하세요."}, {s:"B",en:"Si necesito ayuda, le aviso.",ko:"도움 필요하면 말씀드릴게요.",hl:true} ],
  "compras|1|3": [ {s:"A",en:"Tómese su tiempo.",ko:"천천히 보세요."}, {s:"B",en:"¿Me puede ayudar a buscar algo?",ko:"뭐 좀 찾는 거 도와주실래요?",hl:true} ],
  "compras|1|4": [ {s:"A",en:"¿Qué busca?",ko:"뭐 찾으세요?"}, {s:"B",en:"Busco un regalo para mi madre.",ko:"엄마 선물을 찾고 있어요.",hl:true} ],
  "compras|2|0": [ {s:"A",en:"¿Cuánto cuesta esto?",ko:"이거 얼마예요?",hl:true}, {s:"B",en:"Veinte euros.",ko:"20유로예요."} ],
  "compras|2|1": [ {s:"A",en:"¿Está en rebajas?",ko:"이거 세일 중인가요?",hl:true}, {s:"B",en:"Sí, hoy hay 20% de descuento.",ko:"네, 오늘 20% 할인이에요."} ],
  "compras|2|2": [ {s:"A",en:"Son noventa euros.",ko:"90유로예요."}, {s:"B",en:"Es un poco caro para mí.",ko:"저한텐 좀 비싸네요.",hl:true} ],
  "compras|2|3": [ {s:"A",en:"¿Me puede hacer un descuento?",ko:"좀 깎아주실 수 있나요?",hl:true}, {s:"B",en:"Le puedo quitar un 10%.",ko:"10% 정도 빼드릴 수 있어요."} ],
  "compras|2|4": [ {s:"A",en:"¿Hay algo más barato?",ko:"더 싼 거 있나요?",hl:true}, {s:"B",en:"Sí, mire estos.",ko:"네, 이것들 보세요."} ],
  "compras|3|0": [ {s:"A",en:"Quería devolver esto, por favor.",ko:"이거 반품하고 싶어요.",hl:true}, {s:"B",en:"¿Tiene el ticket?",ko:"영수증 있으세요?"} ],
  "compras|3|1": [ {s:"A",en:"¿Puedo cambiarlo por otra talla?",ko:"다른 사이즈로 교환할 수 있나요?",hl:true}, {s:"B",en:"Claro, ¿qué talla?",ko:"그럼요, 어떤 사이즈로요?"} ],
  "compras|3|2": [ {s:"A",en:"¿Tiene el comprobante?",ko:"증빙 있으세요?"}, {s:"B",en:"Aquí está el ticket.",ko:"여기 영수증이요.",hl:true} ],
  "compras|3|3": [ {s:"A",en:"¿Qué pasa con esto?",ko:"뭐가 문제예요?"}, {s:"B",en:"No me queda bien.",ko:"사이즈가 안 맞아요.",hl:true} ],
  "compras|3|4": [ {s:"A",en:"¿Cuál es su política de devoluciones?",ko:"환불 규정이 어떻게 되나요?",hl:true}, {s:"B",en:"Treinta días con el ticket.",ko:"영수증 있으면 30일이요."} ],
  "compras|4|0": [ {s:"A",en:"¿Cómo va a pagar?",ko:"어떻게 결제하시겠어요?"}, {s:"B",en:"Pago con tarjeta.",ko:"카드로 결제할게요.",hl:true} ],
  "compras|4|1": [ {s:"A",en:"¿Puedo pagar en efectivo?",ko:"현금으로 내도 되나요?",hl:true}, {s:"B",en:"Por supuesto.",ko:"물론이죠."} ],
  "compras|4|2": [ {s:"A",en:"¿Me da una bolsa, por favor?",ko:"봉투 하나 주시겠어요?",hl:true}, {s:"B",en:"Claro, son diez céntimos.",ko:"네, 10센트예요."} ],
  "compras|4|3": [ {s:"A",en:"¿Me da el recibo?",ko:"영수증 주시겠어요?",hl:true}, {s:"B",en:"Aquí tiene.",ko:"여기요."} ],
  "compras|4|4": [ {s:"A",en:"¿Cobran por la bolsa?",ko:"봉투 값 받나요?",hl:true}, {s:"B",en:"Sí, cinco céntimos.",ko:"네, 5센트요."} ],
  "direcciones|0|0": [ {s:"A",en:"Perdone, ¿cómo llego a la estación?",ko:"실례합니다, 역에 어떻게 가나요?",hl:true}, {s:"B",en:"Todo recto, a la izquierda.",ko:"직진하다 왼쪽이요."} ],
  "direcciones|0|1": [ {s:"A",en:"¿Es por aquí el museo?",ko:"박물관이 이쪽인가요?",hl:true}, {s:"B",en:"Sí, siga caminando.",ko:"네, 계속 걸어가세요."} ],
  "direcciones|0|2": [ {s:"A",en:"¿Está lejos de aquí?",ko:"여기서 멀어요?",hl:true}, {s:"B",en:"Unos diez minutos andando.",ko:"걸어서 10분 정도요."} ],
  "direcciones|0|3": [ {s:"A",en:"¿Se puede ir andando?",ko:"걸어갈 수 있어요?",hl:true}, {s:"B",en:"Sí, está cerca.",ko:"네, 가까워요."} ],
  "direcciones|0|4": [ {s:"A",en:"¿Me lo puede mostrar en el mapa?",ko:"지도에서 보여주실 수 있나요?",hl:true}, {s:"B",en:"Claro, estamos aquí.",ko:"네, 우리가 여기 있어요."} ],
  "direcciones|1|0": [ {s:"A",en:"¿Cómo llego al banco?",ko:"은행에 어떻게 가요?"}, {s:"B",en:"Siga todo recto dos calles.",ko:"두 블록 직진하세요.",hl:true} ],
  "direcciones|1|1": [ {s:"A",en:"¿Y después?",ko:"그다음엔요?"}, {s:"B",en:"Gire a la izquierda en la esquina.",ko:"모퉁이에서 왼쪽으로 도세요.",hl:true} ],
  "direcciones|1|2": [ {s:"A",en:"¿Dónde está la entrada?",ko:"입구가 어디예요?"}, {s:"B",en:"Está a la derecha.",ko:"오른쪽에 있어요.",hl:true} ],
  "direcciones|1|3": [ {s:"A",en:"¿La cafetería está lejos?",ko:"카페 멀어요?"}, {s:"B",en:"Está a la vuelta de la esquina.",ko:"바로 모퉁이 돌면 있어요.",hl:true} ],
  "direcciones|1|4": [ {s:"A",en:"¿Lo encontraré?",ko:"찾을 수 있을까요?"}, {s:"B",en:"No tiene pérdida.",ko:"못 찾을 수 없어요.",hl:true} ],
  "direcciones|2|0": [ {s:"A",en:"¿Qué línea va al centro?",ko:"시내로 가는 노선이 뭐예요?",hl:true}, {s:"B",en:"La línea azul.",ko:"파란색 노선이요."} ],
  "direcciones|2|1": [ {s:"A",en:"¿Tengo que hacer transbordo?",ko:"환승해야 하나요?",hl:true}, {s:"B",en:"Sí, una vez.",ko:"네, 한 번이요."} ],
  "direcciones|2|2": [ {s:"A",en:"¿Cuántas paradas faltan?",ko:"몇 정거장 남았어요?",hl:true}, {s:"B",en:"Tres paradas.",ko:"세 정거장이요."} ],
  "direcciones|2|3": [ {s:"A",en:"¿Este autobús va al aeropuerto?",ko:"이 버스 공항 가나요?",hl:true}, {s:"B",en:"No, necesita el 302.",ko:"아뇨, 302번을 타셔야 해요."} ],
  "direcciones|2|4": [ {s:"A",en:"¿Me avisa cuándo bajar?",ko:"내릴 때 알려주실 수 있나요?",hl:true}, {s:"B",en:"Claro, le aviso.",ko:"네, 알려드릴게요."} ],
  "direcciones|3|0": [ {s:"A",en:"¿Me lleva a esta dirección?",ko:"이 주소로 가주시겠어요?",hl:true}, {s:"B",en:"Claro, suba.",ko:"네, 타세요."} ],
  "direcciones|3|1": [ {s:"A",en:"¿Cuánto costará más o menos?",ko:"대략 얼마나 나올까요?",hl:true}, {s:"B",en:"Unos quince euros.",ko:"15유로 정도요."} ],
  "direcciones|3|2": [ {s:"A",en:"¿Puede poner el taxímetro?",ko:"미터기 켜주시겠어요?",hl:true}, {s:"B",en:"Sí, disculpe.",ko:"네, 죄송합니다."} ],
  "direcciones|3|3": [ {s:"A",en:"Tengo un poco de prisa.",ko:"제가 좀 급해요.",hl:true}, {s:"B",en:"Voy por el camino rápido.",ko:"빠른 길로 갈게요."} ],
  "direcciones|3|4": [ {s:"A",en:"Aquí está bien, gracias.",ko:"여기서 내려주시면 돼요.",hl:true}, {s:"B",en:"Son doce euros.",ko:"12유로입니다."} ],
  "viajes|0|0": [ {s:"A",en:"Quería facturar para mi vuelo.",ko:"탑승 수속 하려고요.",hl:true}, {s:"B",en:"Su pasaporte, por favor.",ko:"여권 주세요."} ],
  "viajes|0|1": [ {s:"A",en:"¿Me da un asiento de ventanilla?",ko:"창가 자리로 받을 수 있을까요?",hl:true}, {s:"B",en:"Claro, el 24A.",ko:"네, 24A 자리예요."} ],
  "viajes|0|2": [ {s:"A",en:"¿Lleva equipaje?",ko:"부치실 짐 있으세요?"}, {s:"B",en:"Tengo una maleta para facturar.",ko:"부칠 가방이 하나 있어요.",hl:true} ],
  "viajes|0|3": [ {s:"A",en:"¿El vuelo sale a tiempo?",ko:"비행기 정시 출발하나요?",hl:true}, {s:"B",en:"Sí, sin retraso.",ko:"네, 지연 없어요."} ],
  "viajes|0|4": [ {s:"A",en:"¿De qué puerta sale?",ko:"몇 번 게이트에서 출발하나요?",hl:true}, {s:"B",en:"La puerta 22.",ko:"22번 게이트요."} ],
  "viajes|1|0": [ {s:"A",en:"¿Cuál es el motivo del viaje?",ko:"여행 목적이 뭔가요?"}, {s:"B",en:"Estoy de vacaciones.",ko:"휴가차 왔어요.",hl:true} ],
  "viajes|1|1": [ {s:"A",en:"¿Negocios o turismo?",ko:"출장이세요 관광이세요?"}, {s:"B",en:"Vengo por negocios.",ko:"출장 왔어요.",hl:true} ],
  "viajes|1|2": [ {s:"A",en:"¿Cuánto tiempo se queda?",ko:"얼마나 머무세요?"}, {s:"B",en:"Me quedo dos semanas.",ko:"2주 동안 머물러요.",hl:true} ],
  "viajes|1|3": [ {s:"A",en:"¿Dónde se hospeda?",ko:"어디 묵으세요?"}, {s:"B",en:"Me hospedo en un hotel del centro.",ko:"시내 호텔에 머물러요.",hl:true} ],
  "viajes|1|4": [ {s:"A",en:"Sus documentos, por favor.",ko:"서류 주세요."}, {s:"B",en:"Aquí tiene mi pasaporte.",ko:"여기 여권이요.",hl:true} ],
  "viajes|2|0": [ {s:"A",en:"¿Nos puede hacer una foto?",ko:"저희 사진 좀 찍어주실래요?",hl:true}, {s:"B",en:"¡Claro! Sonrían.",ko:"그럼요! 웃으세요."} ],
  "viajes|2|1": [ {s:"A",en:"¿Dónde está el baño más cercano?",ko:"가장 가까운 화장실이 어디예요?",hl:true}, {s:"B",en:"Pasando la tienda.",ko:"가게 지나서요."} ],
  "viajes|2|2": [ {s:"A",en:"¿Hay wifi gratis aquí?",ko:"여기 무료 와이파이 있나요?",hl:true}, {s:"B",en:"Sí, la clave está en la mesa.",ko:"네, 비밀번호는 테이블에 있어요."} ],
  "viajes|2|3": [ {s:"A",en:"¿A qué hora abren?",ko:"몇 시에 문 열어요?",hl:true}, {s:"B",en:"A las nueve.",ko:"9시에요."} ],
  "viajes|2|4": [ {s:"A",en:"¿Conoce un buen sitio para comer cerca?",ko:"근처에 맛집 아세요?",hl:true}, {s:"B",en:"Sí, hay uno a la vuelta.",ko:"네, 모퉁이에 하나 있어요."} ],
  "viajes|3|0": [ {s:"A",en:"Creo que he perdido el pasaporte.",ko:"여권을 잃어버린 것 같아요.",hl:true}, {s:"B",en:"Vamos a reportarlo.",ko:"신고하죠."} ],
  "viajes|3|1": [ {s:"A",en:"No ha llegado mi maleta.",ko:"제 짐이 안 나왔어요.",hl:true}, {s:"B",en:"Lo siento, la buscamos.",ko:"죄송해요, 찾아볼게요."} ],
  "viajes|3|2": [ {s:"A",en:"He perdido el vuelo de conexión.",ko:"환승 비행기를 놓쳤어요.",hl:true}, {s:"B",en:"Le buscamos otro vuelo.",ko:"다른 편을 찾아드릴게요."} ],
  "viajes|3|3": [ {s:"A",en:"Mi vuelo lleva retraso.",ko:"제 비행기가 지연됐어요.",hl:true}, {s:"B",en:"¿De cuánto es el retraso?",ko:"얼마나 지연됐어요?"} ],
  "viajes|3|4": [ {s:"A",en:"¿Con quién puedo hablar sobre esto?",ko:"이건 누구한테 말해야 하나요?",hl:true}, {s:"B",en:"En aquel mostrador.",ko:"저쪽 데스크에서요."} ],
  "hotel|0|0": [ {s:"A",en:"Tengo una reserva a nombre de Lee.",ko:"Lee 이름으로 예약했어요.",hl:true}, {s:"B",en:"Bienvenido, aquí tiene la llave.",ko:"환영합니다, 여기 열쇠예요."} ],
  "hotel|0|1": [ {s:"A",en:"¿A qué hora es la salida?",ko:"체크아웃은 몇 시예요?",hl:true}, {s:"B",en:"A las doce.",ko:"12시예요."} ],
  "hotel|0|2": [ {s:"A",en:"¿Puedo entrar antes?",ko:"일찍 체크인할 수 있을까요?",hl:true}, {s:"B",en:"Déjeme ver si hay habitación.",ko:"방이 있는지 볼게요."} ],
  "hotel|0|3": [ {s:"A",en:"¿Puedo hacer la salida más tarde?",ko:"체크아웃을 늦게 할 수 있을까요?",hl:true}, {s:"B",en:"Sí, hasta la una.",ko:"네, 1시까지요."} ],
  "hotel|0|4": [ {s:"A",en:"¿Puedo dejar las maletas aquí?",ko:"짐 좀 맡길 수 있나요?",hl:true}, {s:"B",en:"Claro, se las guardamos.",ko:"그럼요, 보관해 드릴게요."} ],
  "hotel|1|0": [ {s:"A",en:"¿Me puede dar más toallas?",ko:"수건 좀 더 받을 수 있을까요?",hl:true}, {s:"B",en:"Por supuesto.",ko:"물론이죠."} ],
  "hotel|1|1": [ {s:"A",en:"¿El desayuno está incluido?",ko:"조식 포함인가요?",hl:true}, {s:"B",en:"Sí, de 7 a 10.",ko:"네, 7시부터 10시까지요."} ],
  "hotel|1|2": [ {s:"A",en:"¿Cuál es la contraseña del wifi?",ko:"와이파이 비밀번호가 뭐예요?",hl:true}, {s:"B",en:"Es 'hotel123'.",ko:"'hotel123'이에요."} ],
  "hotel|1|3": [ {s:"A",en:"¿Me puede pedir un taxi?",ko:"택시 좀 불러주시겠어요?",hl:true}, {s:"B",en:"Claro, llega en cinco minutos.",ko:"네, 5분 안에 와요."} ],
  "hotel|1|4": [ {s:"A",en:"¿Tiene una habitación con mejores vistas?",ko:"전망 더 좋은 방 있나요?",hl:true}, {s:"B",en:"Tenemos una con vista al mar.",ko:"바다 전망 방이 있어요."} ],
  "hotel|2|0": [ {s:"A",en:"El aire acondicionado no funciona.",ko:"에어컨이 안 돼요.",hl:true}, {s:"B",en:"Disculpe, mando a alguien.",ko:"죄송해요, 사람을 보낼게요."} ],
  "hotel|2|1": [ {s:"A",en:"La habitación de al lado hace mucho ruido.",ko:"옆방이 너무 시끄러워요.",hl:true}, {s:"B",en:"Lo siento, me encargo.",ko:"죄송해요, 처리할게요."} ],
  "hotel|2|2": [ {s:"A",en:"No hay agua caliente.",ko:"온수가 안 나와요.",hl:true}, {s:"B",en:"Lo arreglamos enseguida.",ko:"바로 고쳐드릴게요."} ],
  "hotel|2|3": [ {s:"A",en:"¿Puede venir alguien a revisarlo?",ko:"누가 와서 봐줄 수 있을까요?",hl:true}, {s:"B",en:"Sí, en un momento.",ko:"네, 잠시 후에요."} ],
  "hotel|2|4": [ {s:"A",en:"¿Me puede cambiar de habitación?",ko:"다른 방으로 바꿀 수 있을까요?",hl:true}, {s:"B",en:"Por supuesto.",ko:"물론이죠."} ],
  "telefono|0|0": [ {s:"A",en:"Hola, soy Jun, de la empresa ABC.",ko:"안녕하세요, ABC사의 준입니다.",hl:true}, {s:"B",en:"Hola Jun, ¿en qué le ayudo?",ko:"안녕하세요 준, 무엇을 도와드릴까요?"} ],
  "telefono|0|1": [ {s:"A",en:"¿Está el señor Smith?",ko:"스미스 씨 계세요?",hl:true}, {s:"B",en:"Un momento, le paso.",ko:"잠시만요, 연결해 드릴게요."} ],
  "telefono|0|2": [ {s:"A",en:"Llamo por la cita.",ko:"예약 건으로 전화드렸어요.",hl:true}, {s:"B",en:"Claro, ¿su nombre?",ko:"네, 성함이요?"} ],
  "telefono|0|3": [ {s:"A",en:"¿Le pillo en buen momento?",ko:"지금 통화 괜찮으세요?",hl:true}, {s:"B",en:"Sí, dígame.",ko:"네, 말씀하세요."} ],
  "telefono|0|4": [ {s:"A",en:"¿Me puede pasar con el gerente?",ko:"매니저에게 연결해 주시겠어요?",hl:true}, {s:"B",en:"Un momento, por favor.",ko:"잠시만 기다려 주세요."} ],
  "telefono|1|0": [ {s:"A",en:"Hola, ¿es atención al cliente?",ko:"안녕하세요, 고객센터죠?"}, {s:"B",en:"¿Dígame?",ko:"여보세요?",hl:true} ],
  "telefono|1|1": [ {s:"A",en:"¿Puede revisar mi pedido?",ko:"제 주문 확인해 주실래요?"}, {s:"B",en:"Un momento, por favor.",ko:"잠시만 기다려 주세요.",hl:true} ],
  "telefono|1|2": [ {s:"A",en:"¿Está el señor Kim?",ko:"김 씨 계세요?"}, {s:"B",en:"Ahora mismo no está.",ko:"지금 자리에 없어요.",hl:true} ],
  "telefono|1|3": [ {s:"A",en:"Ha salido un momento.",ko:"잠깐 나가셨어요."}, {s:"B",en:"¿Quiere dejar un mensaje?",ko:"메시지 남겨드릴까요?",hl:true} ],
  "telefono|1|4": [ {s:"A",en:"¿Algún mensaje?",ko:"메시지 있으세요?"}, {s:"B",en:"¿Le puede decir que me llame?",ko:"저한테 전화해 달라고 전해주실래요?",hl:true} ],
  "telefono|2|0": [ {s:"A",en:"Perdona, se corta.",ko:"미안, 소리가 끊겨.",hl:true}, {s:"B",en:"Voy a un sitio con cobertura.",ko:"신호 잡히는 데로 갈게."} ],
  "telefono|2|1": [ {s:"A",en:"¿Puede hablar más alto?",ko:"조금 더 크게 말씀해 주시겠어요?",hl:true}, {s:"B",en:"¿Así mejor?",ko:"이제 나아요?"} ],
  "telefono|2|2": [ {s:"A",en:"No te oigo bien.",ko:"잘 안 들려.",hl:true}, {s:"B",en:"Te llamo en un momento.",ko:"조금 있다 다시 걸게."} ],
  "telefono|2|3": [ {s:"A",en:"Hay mala cobertura.",ko:"신호가 안 좋아."}, {s:"B",en:"Te llamo en un momento.",ko:"조금 있다 다시 걸게.",hl:true} ],
  "telefono|2|4": [ {s:"A",en:"...y ese es el plan.",ko:"…그게 계획이에요."}, {s:"B",en:"¿Me lo puede repetir?",ko:"다시 한번 말씀해 주시겠어요?",hl:true} ],
  "trabajo|0|0": [ {s:"A",en:"¿Empezamos?",ko:"시작할까요?",hl:true}, {s:"B",en:"Sí, vamos.",ko:"네, 시작하죠."} ],
  "trabajo|0|1": [ {s:"A",en:"Lo lanzamos el mes que viene.",ko:"다음 달에 출시해요."}, {s:"B",en:"Para aclarar, ¿quieres decir a principios?",ko:"확실히 하자면, 초라는 말씀이세요?",hl:true} ],
  "trabajo|0|2": [ {s:"A",en:"...y el presupuesto está cerrado.",ko:"…그래서 예산은 확정됐어요."}, {s:"B",en:"Perdón que interrumpa, tengo una pregunta.",ko:"끼어들어 죄송한데, 질문이 있어요.",hl:true} ],
  "trabajo|0|3": [ {s:"A",en:"¿Todos lo entendieron?",ko:"다들 이해되셨어요?"}, {s:"B",en:"¿Lo puede explicar otra vez?",ko:"그거 다시 설명해 주시겠어요?",hl:true} ],
  "trabajo|0|4": [ {s:"A",en:"¿Y el presupuesto?",ko:"예산은요?"}, {s:"B",en:"Lo vemos más tarde.",ko:"그건 나중에 다루죠.",hl:true} ],
  "trabajo|1|0": [ {s:"A",en:"¿Qué opción elegimos?",ko:"어느 안으로 갈까요?"}, {s:"B",en:"Yo propondría la primera opción.",ko:"첫 번째 안을 제안하고 싶어요.",hl:true} ],
  "trabajo|1|1": [ {s:"A",en:"Así ahorramos tiempo.",ko:"이러면 시간을 아껴요."}, {s:"B",en:"Eso tiene sentido.",ko:"그거 말 되네요.",hl:true} ],
  "trabajo|1|2": [ {s:"A",en:"Hagámoslo a mi manera.",ko:"제 방식대로 하죠."}, {s:"B",en:"Entiendo tu punto, pero...",ko:"무슨 말인지 알겠는데, 다만…",hl:true} ],
  "trabajo|1|3": [ {s:"A",en:"¿Decidimos ya?",ko:"지금 정할까요?"}, {s:"B",en:"¿Podemos ver primero los números?",ko:"먼저 수치부터 볼 수 있을까요?",hl:true} ],
  "trabajo|1|4": [ {s:"A",en:"¿Y la nueva función?",ko:"새 기능은요?"}, {s:"B",en:"Dejémoslo por ahora.",ko:"이건 일단 보류하죠.",hl:true} ],
  "trabajo|2|0": [ {s:"A",en:"¿Me puedes echar una mano con esto?",ko:"이것 좀 도와줄래요?",hl:true}, {s:"B",en:"Claro, ¿qué necesitas?",ko:"그럼요, 뭐가 필요해요?"} ],
  "trabajo|2|1": [ {s:"A",en:"¿Tienes un minuto?",ko:"잠깐 시간 있어요?",hl:true}, {s:"B",en:"Sí, ¿qué pasa?",ko:"네, 무슨 일이에요?"} ],
  "trabajo|2|2": [ {s:"A",en:"Es un proyecto grande.",ko:"큰 프로젝트네요."}, {s:"B",en:"Avísame si necesitas algo.",ko:"필요한 거 있으면 말해줘요.",hl:true} ],
  "trabajo|2|3": [ {s:"A",en:"¿Quién hace el informe?",ko:"보고서는 누가 해요?"}, {s:"B",en:"Yo me encargo.",ko:"제가 처리할게요.",hl:true} ],
  "trabajo|2|4": [ {s:"A",en:"No sé cómo funciona esto.",ko:"이거 어떻게 하는지 모르겠어요."}, {s:"B",en:"¿Me lo puedes explicar paso a paso?",ko:"차근차근 설명해 줄 수 있어요?",hl:true} ],
  "trabajo|3|0": [ {s:"A",en:"¿Cuál es la fecha límite?",ko:"마감이 언제예요?",hl:true}, {s:"B",en:"El viernes.",ko:"금요일이요."} ],
  "trabajo|3|1": [ {s:"A",en:"¿Podemos aplazar el plazo?",ko:"마감을 좀 미룰 수 있을까요?",hl:true}, {s:"B",en:"Quizá un par de días.",ko:"이틀 정도는요."} ],
  "trabajo|3|2": [ {s:"A",en:"¿Cuándo lo tendré?",ko:"언제 받을 수 있을까요?"}, {s:"B",en:"Te lo envío el viernes.",ko:"금요일까지 보낼게요.",hl:true} ],
  "trabajo|3|3": [ {s:"A",en:"¿Cómo va el proyecto?",ko:"프로젝트 어떻게 돼가요?"}, {s:"B",en:"Voy un poco retrasado con esto.",ko:"이거 조금 밀렸어요.",hl:true} ],
  "trabajo|3|4": [ {s:"A",en:"Necesito el archivo ya.",ko:"그 파일 급해요."}, {s:"B",en:"¿Me lo puede mandar cuanto antes?",ko:"가능한 빨리 보내주실 수 있나요?",hl:true} ],
  "peticiones|0|0": [ {s:"A",en:"¿Podrías ayudarme un momento?",ko:"잠깐만 도와줄 수 있어요?",hl:true}, {s:"B",en:"Claro, ¿qué es?",ko:"그럼요, 뭔데요?"} ],
  "peticiones|0|1": [ {s:"A",en:"¿Te importaría abrir la ventana?",ko:"창문 좀 열어주시겠어요?",hl:true}, {s:"B",en:"En absoluto.",ko:"그럼요(전혀요)."} ],
  "peticiones|0|2": [ {s:"A",en:"¿Me harías un favor?",ko:"부탁 하나 들어줄 수 있어요?",hl:true}, {s:"B",en:"Claro, dime.",ko:"그럼요, 말해요."} ],
  "peticiones|0|3": [ {s:"A",en:"¿Sería posible cambiar la reunión?",ko:"회의를 옮기는 게 가능할까요?",hl:true}, {s:"B",en:"Sí, ¿el jueves?",ko:"네, 목요일 어때요?"} ],
  "peticiones|0|4": [ {s:"A",en:"Si no es molestia, ¿podrías revisar esto?",ko:"번거롭지 않으면, 이거 봐줄 수 있어요?",hl:true}, {s:"B",en:"Con gusto, envíamelo.",ko:"기꺼이요, 보내줘요."} ],
  "peticiones|1|0": [ {s:"A",en:"¿Puedo usar esto un momento?",ko:"이거 잠깐 써도 돼요?",hl:true}, {s:"B",en:"Sí, adelante.",ko:"네, 그러세요."} ],
  "peticiones|1|1": [ {s:"A",en:"¿Está bien si me siento aquí?",ko:"여기 앉아도 될까요?",hl:true}, {s:"B",en:"Claro, siéntate.",ko:"그럼요, 앉으세요."} ],
  "peticiones|1|2": [ {s:"A",en:"¿Te importa si me uno?",ko:"같이 껴도 될까요?",hl:true}, {s:"B",en:"Para nada, ven.",ko:"전혀요, 오세요."} ],
  "peticiones|1|3": [ {s:"A",en:"¿Le importa si me voy antes?",ko:"일찍 가도 될까요?",hl:true}, {s:"B",en:"No, adelante.",ko:"네, 그러세요."} ],
  "peticiones|1|4": [ {s:"A",en:"¿Puedo usar el baño?",ko:"화장실 좀 써도 될까요?",hl:true}, {s:"B",en:"Sí, al fondo.",ko:"네, 안쪽에 있어요."} ],
  "peticiones|2|0": [ {s:"A",en:"¿Por qué no tomamos un café?",ko:"커피 한잔 하는 거 어때요?",hl:true}, {s:"B",en:"¡Buena idea, vamos!",ko:"좋은 생각이에요, 가요!"} ],
  "peticiones|2|1": [ {s:"A",en:"¿Qué tal si quedamos a las siete?",ko:"7시에 만나는 거 어때요?",hl:true}, {s:"B",en:"A las siete me va bien.",ko:"7시 괜찮아요."} ],
  "peticiones|2|2": [ {s:"A",en:"Estoy cansado.",ko:"피곤하네요."}, {s:"B",en:"Vamos a descansar un poco.",ko:"잠깐 쉬어요.",hl:true} ],
  "peticiones|2|3": [ {s:"A",en:"¿Dónde comemos?",ko:"어디서 먹을까요?"}, {s:"B",en:"Podríamos probar el sitio nuevo.",ko:"새로 생긴 데 가봐도 되고요.",hl:true} ],
  "peticiones|2|4": [ {s:"A",en:"¿Y si salimos ya?",ko:"지금 출발하는 거 어때요?",hl:true}, {s:"B",en:"Buena idea, vamos.",ko:"좋아요, 가요."} ],
  "peticiones|3|0": [ {s:"A",en:"¿Me pasas el archivo?",ko:"파일 좀 보내줄래요?"}, {s:"B",en:"Claro, sin problema.",ko:"그럼요, 문제없어요.",hl:true} ],
  "peticiones|3|1": [ {s:"A",en:"¿Me ayudas mañana?",ko:"내일 도와줄래요?"}, {s:"B",en:"Con mucho gusto.",ko:"기꺼이 할게요.",hl:true} ],
  "peticiones|3|2": [ {s:"A",en:"¿Cenamos juntos?",ko:"저녁 같이 먹을래요?"}, {s:"B",en:"Me encantaría, pero estoy ocupado.",ko:"그러고 싶은데, 제가 좀 바빠서요.",hl:true} ],
  "peticiones|3|3": [ {s:"A",en:"¿Estás libre esta noche?",ko:"오늘 밤 시간 돼요?"}, {s:"B",en:"¿Quizá en otro momento?",ko:"다음 기회에 어때요?",hl:true} ],
  "peticiones|3|4": [ {s:"A",en:"¿Aceptas la oferta?",ko:"그 제안 받을 거예요?"}, {s:"B",en:"Déjame pensarlo.",ko:"좀 생각해 볼게요.",hl:true} ],
  "opiniones|0|0": [ {s:"A",en:"¿Qué te parece el plan?",ko:"그 계획 어떻게 생각해요?"}, {s:"B",en:"Para mí, es una buena idea.",ko:"제 생각엔 좋은 생각이에요.",hl:true} ],
  "opiniones|0|1": [ {s:"A",en:"¿Lo compramos?",ko:"이거 살까요?"}, {s:"B",en:"Creo que es demasiado caro.",ko:"너무 비싼 것 같아요.",hl:true} ],
  "opiniones|0|2": [ {s:"A",en:"¿Qué hacemos?",ko:"어떻게 할까요?"}, {s:"B",en:"Tal y como lo veo, hay dos opciones.",ko:"제가 보기엔 선택지가 둘이에요.",hl:true} ],
  "opiniones|0|3": [ {s:"A",en:"¿Funcionará?",ko:"잘 될까요?"}, {s:"B",en:"La verdad, no estoy seguro.",ko:"솔직히 잘 모르겠어요.",hl:true} ],
  "opiniones|0|4": [ {s:"A",en:"¿Vale la pena?",ko:"그럴 가치 있어요?"}, {s:"B",en:"Depende, la verdad.",ko:"사실 경우에 따라 달라요.",hl:true} ],
  "opiniones|1|0": [ {s:"A",en:"Deberíamos empezar antes.",ko:"더 일찍 시작해야 해요."}, {s:"B",en:"Estoy totalmente de acuerdo.",ko:"완전 동의해요.",hl:true} ],
  "opiniones|1|1": [ {s:"A",en:"Quizá necesitamos más gente.",ko:"사람이 더 필요할지도요."}, {s:"B",en:"Exacto, eso pensaba yo.",ko:"맞아요, 저도 그렇게 생각했어요.",hl:true} ],
  "opiniones|1|2": [ {s:"A",en:"Puede ser arriesgado.",ko:"위험할 수도 있어요."}, {s:"B",en:"Tienes razón.",ko:"네 말이 맞아.",hl:true} ],
  "opiniones|1|3": [ {s:"A",en:"Hay que cuidar la calidad.",ko:"품질에 신경 써야 해요."}, {s:"B",en:"No podría estar más de acuerdo.",ko:"전적으로 동의해요.",hl:true} ],
  "opiniones|1|4": [ {s:"A",en:"Cada vez es más caro.",ko:"점점 비싸지네요."}, {s:"B",en:"Es verdad.",ko:"그건 맞아요.",hl:true} ],
  "opiniones|2|0": [ {s:"A",en:"Cancelémoslo.",ko:"취소하죠."}, {s:"B",en:"Entiendo lo que dices, pero no estoy seguro.",ko:"무슨 말인지 알겠는데, 전 확신이 안 서요.",hl:true} ],
  "opiniones|2|1": [ {s:"A",en:"Es claramente lo mejor.",ko:"이게 분명 최선이에요."}, {s:"B",en:"Me temo que no estoy de acuerdo.",ko:"죄송하지만 저는 생각이 달라요.",hl:true} ],
  "opiniones|2|2": [ {s:"A",en:"Hay que recortar el presupuesto.",ko:"예산을 줄여야 해요."}, {s:"B",en:"Es una forma de verlo, pero...",ko:"그렇게 볼 수도 있지만, 다만…",hl:true} ],
  "opiniones|2|3": [ {s:"A",en:"A todos les encantará.",ko:"다들 좋아할 거예요."}, {s:"B",en:"Yo lo veo distinto.",ko:"저는 다르게 봐요.",hl:true} ],
  "opiniones|2|4": [ {s:"A",en:"Seguro que funciona.",ko:"분명 될 거예요."}, {s:"B",en:"¿Has pensado en la otra parte?",ko:"반대편 입장도 생각해 봤어요?",hl:true} ],
  "emociones|0|0": [ {s:"A",en:"¡Nos vamos de viaje!",ko:"우리 여행 가!"}, {s:"B",en:"¡Estoy muy contento!",ko:"너무 기뻐요!",hl:true} ],
  "emociones|0|1": [ {s:"A",en:"¿Planes para el sábado?",ko:"토요일 계획 있어?"}, {s:"B",en:"¡No veo la hora del fin de semana!",ko:"주말이 너무 기다려져요!",hl:true} ],
  "emociones|0|2": [ {s:"A",en:"Te traje tu pastel favorito.",ko:"네가 좋아하는 케이크 사 왔어."}, {s:"B",en:"Esto me alegró el día.",ko:"덕분에 오늘 하루가 행복해요.",hl:true} ],
  "emociones|0|3": [ {s:"A",en:"¡Te aceptaron!",ko:"너 합격했대!"}, {s:"B",en:"¡Qué buena noticia!",ko:"정말 좋은 소식이에요!",hl:true} ],
  "emociones|0|4": [ {s:"A",en:"Te arreglé la bici gratis.",ko:"네 자전거 공짜로 고쳐놨어."}, {s:"B",en:"¡Qué guay!",ko:"완전 멋지다!",hl:true} ],
  "emociones|1|0": [ {s:"A",en:"Gané la lotería.",ko:"나 복권 당첨됐어."}, {s:"B",en:"¡No me digas! ¿En serio?",ko:"말도 안 돼! 진짜?",hl:true} ],
  "emociones|1|1": [ {s:"A",en:"Se casan en junio.",ko:"걔네 6월에 결혼해."}, {s:"B",en:"¡No me lo puedo creer!",ko:"믿기지 않아요!",hl:true} ],
  "emociones|1|2": [ {s:"A",en:"La tienda cerró.",ko:"그 가게 문 닫았어."}, {s:"B",en:"¡Qué sorpresa!",ko:"정말 놀랍네요!",hl:true} ],
  "emociones|1|3": [ {s:"A",en:"Dejó el trabajo de repente.",ko:"걔 갑자기 일 그만뒀어."}, {s:"B",en:"No me lo esperaba.",ko:"전혀 예상 못 했어요.",hl:true} ],
  "emociones|1|4": [ {s:"A",en:"Nos mudamos a Canadá.",ko:"우리 캐나다로 이사 가."}, {s:"B",en:"Espera, ¿qué?",ko:"잠깐, 뭐라고?",hl:true} ],
  "emociones|2|0": [ {s:"A",en:"Suspendí el examen.",ko:"나 시험 떨어졌어."}, {s:"B",en:"Lo siento mucho.",ko:"정말 유감이야.",hl:true} ],
  "emociones|2|1": [ {s:"A",en:"Trabajo día y noche.",ko:"밤낮으로 일해."}, {s:"B",en:"Eso debe de ser muy difícil.",ko:"정말 힘들겠어요.",hl:true} ],
  "emociones|2|2": [ {s:"A",en:"No sé cómo lo haré.",ko:"어떻게 할지 모르겠어."}, {s:"B",en:"Si necesitas algo, aquí estoy.",ko:"필요한 거 있으면 언제든 말해요.",hl:true} ],
  "emociones|2|3": [ {s:"A",en:"No estoy listo para decidir.",ko:"결정할 준비가 안 됐어."}, {s:"B",en:"Tómate el tiempo que necesites.",ko:"천천히 시간 가지세요.",hl:true} ],
  "emociones|2|4": [ {s:"A",en:"Todo va mal.",ko:"다 엉망이야."}, {s:"B",en:"Todo va a salir bien.",ko:"다 잘될 거예요.",hl:true} ],
  "emociones|3|0": [ {s:"A",en:"¿Estás bien?",ko:"괜찮아?"}, {s:"B",en:"Estoy un poco estresado.",ko:"좀 스트레스 받았어요.",hl:true} ],
  "emociones|3|1": [ {s:"A",en:"La impresora se atascó otra vez.",ko:"프린터가 또 걸렸어."}, {s:"B",en:"Esto es muy frustrante.",ko:"이거 진짜 답답하네요.",hl:true} ],
  "emociones|3|2": [ {s:"A",en:"Mañana salen los resultados.",ko:"내일 결과 나와."}, {s:"B",en:"Estoy preocupado por eso.",ko:"그게 좀 걱정돼요.",hl:true} ],
  "emociones|3|3": [ {s:"A",en:"¿Qué vas a hacer?",ko:"어떻게 할 거야?"}, {s:"B",en:"No sé qué hacer.",ko:"어떻게 해야 할지 모르겠어요.",hl:true} ],
  "emociones|3|4": [ {s:"A",en:"Te ves decaído.",ko:"기운 없어 보여."}, {s:"B",en:"Ha sido una semana dura.",ko:"힘든 한 주였어요.",hl:true} ],
  "problemas|0|0": [ {s:"A",en:"Hay un problema con mi pedido.",ko:"주문에 문제가 좀 있어요.",hl:true}, {s:"B",en:"Lo siento, lo reviso.",ko:"죄송해요, 확인할게요."} ],
  "problemas|0|1": [ {s:"A",en:"Esto no es lo que esperaba.",ko:"이건 제가 기대한 것과 달라요.",hl:true}, {s:"B",en:"Entiendo, veamos qué hacemos.",ko:"이해해요, 어떻게 할지 볼게요."} ],
  "problemas|0|2": [ {s:"A",en:"Quería hablar con el encargado.",ko:"책임자와 얘기하고 싶어요.",hl:true}, {s:"B",en:"Por supuesto, un momento.",ko:"그럼요, 잠시만요."} ],
  "problemas|0|3": [ {s:"A",en:"Llevo más de una hora esperando.",ko:"한 시간 넘게 기다리고 있어요.",hl:true}, {s:"B",en:"Disculpe la demora.",ko:"지연돼서 죄송합니다."} ],
  "problemas|0|4": [ {s:"A",en:"¿Lo puede revisar, por favor?",ko:"이거 좀 알아봐 주실 수 있나요?",hl:true}, {s:"B",en:"Claro, ahora mismo.",ko:"그럼요, 지금요."} ],
  "problemas|1|0": [ {s:"A",en:"Quería un reembolso, por favor.",ko:"환불 부탁드려요.",hl:true}, {s:"B",en:"Sin problema, lo tramito.",ko:"네, 처리해 드릴게요."} ],
  "problemas|1|1": [ {s:"A",en:"Está roto. ¿Me lo puede cambiar?",ko:"고장 났어요. 교체해 주실 수 있나요?",hl:true}, {s:"B",en:"Claro, aquí tiene otro.",ko:"그럼요, 새것 여기요."} ],
  "problemas|1|2": [ {s:"A",en:"La app se cierra sola.",ko:"앱이 자꾸 꺼져요."}, {s:"B",en:"¿Cómo podemos solucionarlo?",ko:"이거 어떻게 해결할 수 있을까요?",hl:true} ],
  "problemas|1|3": [ {s:"A",en:"El envío llegó tarde otra vez.",ko:"배송이 또 늦었어요."}, {s:"B",en:"¿Qué puede hacer al respecto?",ko:"이 건에 대해 어떻게 해주실 수 있나요?",hl:true} ],
  "problemas|1|4": [ {s:"A",en:"El vuelo está completo.",ko:"항공편이 만석이에요."}, {s:"B",en:"¿Hay algo que pueda hacer?",ko:"해주실 수 있는 게 있을까요?",hl:true} ],
  "problemas|2|0": [ {s:"A",en:"Enviaste el archivo equivocado.",ko:"파일을 잘못 보냈어요."}, {s:"B",en:"Lo siento mucho.",ko:"정말 죄송해요.",hl:true} ],
  "problemas|2|1": [ {s:"A",en:"El informe tenía errores.",ko:"보고서에 오류가 있었어요."}, {s:"B",en:"Fue culpa mía.",ko:"그건 제 잘못이에요.",hl:true} ],
  "problemas|2|2": [ {s:"A",en:"Ese es mi asiento.",ko:"거기 제 자리예요."}, {s:"B",en:"Perdón, no me di cuenta.",ko:"미안, 몰랐어.",hl:true} ],
  "problemas|2|3": [ {s:"A",en:"Nos cobraron dos veces.",ko:"이중으로 청구됐어요."}, {s:"B",en:"Disculpe la confusión.",ko:"혼선이 있었던 점 사과드려요.",hl:true} ],
  "problemas|2|4": [ {s:"A",en:"Tenga más cuidado, por favor.",ko:"다음엔 조심해 주세요."}, {s:"B",en:"No volverá a pasar.",ko:"다시는 이런 일 없을 거예요.",hl:true} ],
  "problemas|3|0": [ {s:"A",en:"Perdón, derramé el café.",ko:"미안해요, 커피 흘렸어요."}, {s:"B",en:"No pasa nada.",ko:"괜찮아요.",hl:true} ],
  "problemas|3|1": [ {s:"A",en:"Creo que llegué tarde.",ko:"제가 좀 늦은 것 같아요."}, {s:"B",en:"Tranquilo, no hay problema.",ko:"괜찮아요, 문제없어요.",hl:true} ],
  "problemas|3|2": [ {s:"A",en:"Rompí tu taza, perdón.",ko:"네 컵 깼어, 미안해."}, {s:"B",en:"No te preocupes.",ko:"신경 쓰지 마.",hl:true} ],
  "problemas|3|3": [ {s:"A",en:"El tren se retrasó, perdón.",ko:"기차가 지연돼서 미안해요."}, {s:"B",en:"Son cosas que pasan.",ko:"그런 일도 있는 거죠.",hl:true} ],
  "problemas|3|4": [ {s:"A",en:"Siento mucho el error.",ko:"실수 정말 죄송해요."}, {s:"B",en:"Disculpa aceptada.",ko:"사과 받아들일게요.",hl:true} ],
  "salud|0|0": [ {s:"A",en:"¿Qué le pasa?",ko:"어디가 안 좋으세요?"}, {s:"B",en:"Me duele la cabeza.",ko:"머리가 아파요.",hl:true} ],
  "salud|0|1": [ {s:"A",en:"¿Desde cuándo se siente mal?",ko:"언제부터 아프셨어요?"}, {s:"B",en:"Tengo fiebre desde ayer.",ko:"어제부터 열이 나요.",hl:true} ],
  "salud|0|2": [ {s:"A",en:"¿Dónde le duele?",ko:"어디가 아파요?"}, {s:"B",en:"Me duele el estómago.",ko:"배가 아파요.",hl:true} ],
  "salud|0|3": [ {s:"A",en:"¿Se encuentra bien?",ko:"괜찮으세요?"}, {s:"B",en:"Estoy mareado.",ko:"어지러워요.",hl:true} ],
  "salud|0|4": [ {s:"A",en:"No tiene buena cara.",ko:"안색이 안 좋아요."}, {s:"B",en:"Creo que estoy resfriado.",ko:"감기에 걸린 것 같아요.",hl:true} ],
  "salud|1|0": [ {s:"A",en:"Quería ver a un médico.",ko:"진료를 받고 싶어요.",hl:true}, {s:"B",en:"¿Tiene cita?",ko:"예약하셨나요?"} ],
  "salud|1|1": [ {s:"A",en:"¿Necesito receta para esto?",ko:"이거 처방전이 필요한가요?",hl:true}, {s:"B",en:"No, es de venta libre.",ko:"아뇨, 처방전 없이 살 수 있어요."} ],
  "salud|1|2": [ {s:"A",en:"¿Tiene algo para la tos?",ko:"기침에 먹는 약 있나요?",hl:true}, {s:"B",en:"Sí, pruebe este jarabe.",ko:"네, 이 시럽 드셔보세요."} ],
  "salud|1|3": [ {s:"A",en:"¿Tiene alergias?",ko:"알레르기 있으세요?"}, {s:"B",en:"Soy alérgico a la penicilina.",ko:"저는 페니실린 알레르기가 있어요.",hl:true} ],
  "salud|1|4": [ {s:"A",en:"¿Cada cuánto lo tomo?",ko:"이거 얼마나 자주 먹어야 하나요?",hl:true}, {s:"B",en:"Dos veces al día.",ko:"하루 두 번이요."} ],
  "salud|2|0": [ {s:"A",en:"¡Ayuda! ¡Llamen una ambulancia!",ko:"도와주세요! 구급차 불러주세요!",hl:true}, {s:"B",en:"¡Ya llamo, tranquilo!",ko:"지금 전화할게요, 진정하세요!"} ],
  "salud|2|1": [ {s:"A",en:"No puede aparcar aquí.",ko:"여기 주차 안 돼요."}, {s:"B",en:"Es una emergencia.",ko:"응급 상황이에요.",hl:true} ],
  "salud|2|2": [ {s:"A",en:"¿Qué pasó?",ko:"무슨 일이에요?"}, {s:"B",en:"Hay alguien herido.",ko:"누가 다쳤어요.",hl:true} ],
  "salud|2|3": [ {s:"A",en:"¿Dónde está el hospital más cercano?",ko:"가장 가까운 병원이 어디예요?",hl:true}, {s:"B",en:"Dos calles, a la izquierda.",ko:"두 블록 가서 왼쪽이요."} ],
  "salud|2|4": [ {s:"A",en:"Necesito ayuda ahora mismo.",ko:"지금 당장 도움이 필요해요.",hl:true}, {s:"B",en:"Tranquilo, estoy aquí.",ko:"진정하세요, 제가 있어요."} ],
  "dia-a-dia|0|0": [ {s:"A",en:"¿Estás libre este finde?",ko:"이번 주말에 시간 돼?",hl:true}, {s:"B",en:"Creo que sí, ¿por qué?",ko:"아마? 왜?"} ],
  "dia-a-dia|0|1": [ {s:"A",en:"¿Te apetece cenar algún día?",ko:"언제 저녁 같이 먹을래?",hl:true}, {s:"B",en:"¡Claro! ¿El viernes?",ko:"좋아! 금요일?"} ],
  "dia-a-dia|0|2": [ {s:"A",en:"Te echo de menos.",ko:"보고 싶어."}, {s:"B",en:"A ver si quedamos pronto.",ko:"조만간 보자.",hl:true} ],
  "dia-a-dia|0|3": [ {s:"A",en:"¿A qué hora te viene bien?",ko:"몇 시가 괜찮아?",hl:true}, {s:"B",en:"Después de las seis.",ko:"6시 이후면 돼."} ],
  "dia-a-dia|0|4": [ {s:"A",en:"¿Cine o cena?",ko:"영화 볼래 저녁 먹을래?"}, {s:"B",en:"Por mí, lo que sea.",ko:"난 아무거나 다 좋아.",hl:true} ],
  "dia-a-dia|1|0": [ {s:"A",en:"Ayer conocí a un famoso.",ko:"나 어제 연예인 만났어."}, {s:"B",en:"¿En serio?",ko:"진짜?",hl:true} ],
  "dia-a-dia|1|1": [ {s:"A",en:"Conseguí un trabajo nuevo.",ko:"나 새 직장 구했어."}, {s:"B",en:"¡Qué guay!",ko:"완전 멋지다!",hl:true} ],
  "dia-a-dia|1|2": [ {s:"A",en:"Cancelaron mi vuelo.",ko:"내 비행기 취소됐어."}, {s:"B",en:"¡Qué pena!",ko:"아이고, 안됐다!",hl:true} ],
  "dia-a-dia|1|3": [ {s:"A",en:"Estoy agotado hoy.",ko:"나 오늘 너무 피곤해."}, {s:"B",en:"Yo igual.",ko:"나도 그래.",hl:true} ],
  "dia-a-dia|1|4": [ {s:"A",en:"Este calor es insoportable.",ko:"이 더위 진짜 못 참겠어."}, {s:"B",en:"¡Y que lo digas!",ko:"내 말이!",hl:true} ],
  "dia-a-dia|2|0": [ {s:"A",en:"¿Qué tal todo?",ko:"요즘 다 어때?",hl:true}, {s:"B",en:"Muy bien, gracias.",ko:"아주 좋아, 고마워."} ],
  "dia-a-dia|2|1": [ {s:"A",en:"¿Cómo está tu familia?",ko:"가족들은 잘 지내?",hl:true}, {s:"B",en:"Todos bien, gracias.",ko:"다들 잘 지내, 고마워."} ],
  "dia-a-dia|2|2": [ {s:"A",en:"¿Alguna novedad?",ko:"뭐 새로운 일 있어?",hl:true}, {s:"B",en:"¡Adopté un perrito!",ko:"나 강아지 입양했어!"} ],
  "dia-a-dia|2|3": [ {s:"A",en:"Esto fue divertido.",ko:"오늘 즐거웠어."}, {s:"B",en:"Tenemos que hacer esto más a menudo.",ko:"우리 이거 더 자주 하자.",hl:true} ],
  "dia-a-dia|2|4": [ {s:"A",en:"¡Ya es diciembre!",ko:"벌써 12월이야!"}, {s:"B",en:"Cómo pasa el tiempo, ¿eh?",ko:"시간 진짜 빠르다, 그치?",hl:true} ],
  "dia-a-dia|3|0": [ {s:"A",en:"Es complicado, ¿sabes lo que digo?",ko:"좀 복잡해, 무슨 말인지 알지?",hl:true}, {s:"B",en:"Sí, te entiendo.",ko:"응, 알지."} ],
  "dia-a-dia|3|1": [ {s:"A",en:"¿Cuál es la respuesta?",ko:"답이 뭐야?"}, {s:"B",en:"A ver, déjame pensar...",ko:"음, 생각 좀 해보고…",hl:true} ],
  "dia-a-dia|3|2": [ {s:"A",en:"¿Te gustó la película?",ko:"그 영화 좋았어?"}, {s:"B",en:"La verdad es que...",ko:"솔직히 말하면…",hl:true} ],
  "dia-a-dia|3|3": [ {s:"A",en:"¿Estás enfadado?",ko:"화났어?"}, {s:"B",en:"O sea, está bien.",ko:"그러니까, 뭐 괜찮아.",hl:true} ],
  "dia-a-dia|3|4": [ {s:"A",en:"...perdón, me distraje.",ko:"…미안, 딴 데 정신 팔렸어."}, {s:"B",en:"Bueno, ¿por dónde íbamos?",ko:"아무튼, 우리 어디까지 얘기했지?",hl:true} ]
};
