/* 문장별 예시 대화 — 키: "<situationId>|<groupIndex>|<exampleIndex>"
 * 각 줄: { s:"A"|"B", en, ko, hl?:true(해당 문장이 쓰인 줄) }
 * 엔진은 이 데이터가 있는 문장에만 💬 버튼을 보여줍니다.
 */
window.DIALOGS = {
  "greetings|0|0": [ {s:"A",en:"Hey, how's it going?",ko:"안녕, 어떻게 지내?",hl:true}, {s:"B",en:"Good! Just heading to work.",ko:"좋아! 출근하는 길이야."} ],
  "greetings|0|1": [ {s:"A",en:"How are you doing today?",ko:"오늘 어떻게 지내세요?",hl:true}, {s:"B",en:"Doing well, thanks for asking.",ko:"잘 지내요, 물어봐 줘서 고마워요."} ],
  "greetings|0|2": [ {s:"A",en:"Good to see you. How have you been?",ko:"반가워요. 그동안 어떻게 지냈어요?",hl:true}, {s:"B",en:"Busy, but good. You?",ko:"바빴지만 좋았어요. 당신은요?"} ],
  "greetings|0|3": [ {s:"A",en:"How's everything?",ko:"다 잘 지내?"}, {s:"B",en:"Pretty good, thanks. How about you?",ko:"꽤 좋아요, 고마워요. 당신은요?",hl:true} ],
  "greetings|0|4": [ {s:"A",en:"How have you been?",ko:"그동안 어떻게 지냈어?"}, {s:"B",en:"Can't complain. Same as always.",ko:"그럭저럭이요. 늘 똑같죠.",hl:true} ],
  "greetings|1|0": [ {s:"A",en:"What have you been up to lately?",ko:"요즘 뭐 하고 지냈어요?",hl:true}, {s:"B",en:"Just work, mostly. You?",ko:"거의 일만 했어요. 당신은요?"} ],
  "greetings|1|1": [ {s:"A",en:"Anything exciting going on?",ko:"뭐 신나는 일 있어?"}, {s:"B",en:"Not much, just working a lot.",ko:"별거 없어요, 그냥 일만 많이 했어요.",hl:true} ],
  "greetings|1|2": [ {s:"A",en:"You look tired.",ko:"피곤해 보여."}, {s:"B",en:"I've been pretty busy with work.",ko:"일 때문에 꽤 바빴어요.",hl:true} ],
  "greetings|1|3": [ {s:"A",en:"How's life these days?",ko:"요즘 사는 거 어때?"}, {s:"B",en:"Just the usual, you know.",ko:"뭐 늘 똑같죠.",hl:true} ],
  "greetings|1|4": [ {s:"A",en:"Any news?",ko:"새 소식 있어?"}, {s:"B",en:"I started learning English again!",ko:"다시 영어 공부 시작했어요!",hl:true} ],
  "greetings|2|0": [ {s:"A",en:"Hey! It's been a while.",ko:"야! 오랜만이다.",hl:true}, {s:"B",en:"It really has! Good to see you.",ko:"진짜 그래! 반갑다."} ],
  "greetings|2|1": [ {s:"A",en:"Long time no see! How are things?",ko:"오랜만이야! 잘 지내?",hl:true}, {s:"B",en:"Great, thanks! You look well.",ko:"잘 지내, 고마워! 너 좋아 보인다."} ],
  "greetings|2|2": [ {s:"A",en:"It feels like forever since we last met.",ko:"마지막으로 만난 지 정말 오래된 것 같아.",hl:true}, {s:"B",en:"I know, way too long.",ko:"그러게, 너무 오래됐어."} ],
  "greetings|2|3": [ {s:"A",en:"We should catch up sometime.",ko:"언제 한번 회포 풀자.",hl:true}, {s:"B",en:"Definitely. How about this weekend?",ko:"당연하지. 이번 주말 어때?"} ],
  "greetings|2|4": [ {s:"A",en:"Let's not leave it so long next time.",ko:"다음엔 이렇게 오래 안 보지 말자.",hl:true}, {s:"B",en:"Agreed. Let's plan something soon.",ko:"동의해. 조만간 뭐라도 잡자."} ],
  "greetings|3|0": [ {s:"A",en:"Nice weather we're having, isn't it?",ko:"요즘 날씨 좋죠?",hl:true}, {s:"B",en:"Beautiful. Perfect for a walk.",ko:"정말 좋아요. 산책하기 딱이에요."} ],
  "greetings|3|1": [ {s:"A",en:"It's freezing today, isn't it?",ko:"오늘 진짜 춥네요.",hl:true}, {s:"B",en:"Tell me about it. I forgot my gloves.",ko:"그러게요. 장갑을 깜빡했어요."} ],
  "greetings|3|2": [ {s:"A",en:"Looks like it's going to rain.",ko:"비 올 것 같아요.",hl:true}, {s:"B",en:"Yeah, I'd bring an umbrella.",ko:"네, 우산 챙기는 게 좋겠어요."} ],
  "greetings|3|3": [ {s:"A",en:"This rain won't stop.",ko:"비가 안 그치네."}, {s:"B",en:"I hope it clears up by the weekend.",ko:"주말까지는 날이 개면 좋겠어요.",hl:true} ],
  "greetings|3|4": [ {s:"A",en:"Can you believe this heat?",ko:"이 더위 진짜 말도 안 되죠?",hl:true}, {s:"B",en:"It's brutal. I'm staying inside.",ko:"끔찍해요. 저는 안에 있을래요."} ],
  "greetings|4|0": [ {s:"A",en:"Alright, take care!",ko:"그래, 잘 지내!",hl:true}, {s:"B",en:"You too! See you soon.",ko:"너도! 곧 보자."} ],
  "greetings|4|1": [ {s:"A",en:"I'd better go. See you around!",ko:"나 가야겠다. 또 봐요!",hl:true}, {s:"B",en:"Bye! Take it easy.",ko:"잘 가요! 살살 해요."} ],
  "greetings|4|2": [ {s:"A",en:"Have a good one!",ko:"좋은 하루 보내요!",hl:true}, {s:"B",en:"Thanks, you too!",ko:"고마워요, 당신도요!"} ],
  "greetings|4|3": [ {s:"A",en:"Catch you later.",ko:"나중에 봐.",hl:true}, {s:"B",en:"Sounds good. Later!",ko:"그래. 이따 봐!"} ],
  "greetings|4|4": [ {s:"A",en:"It was great seeing you.",ko:"만나서 정말 반가웠어요.",hl:true}, {s:"B",en:"Likewise! Let's do it again.",ko:"저도요! 또 봐요."} ],
  "intro|0|0": [ {s:"A",en:"Hi, I'm Jun. Nice to meet you.",ko:"안녕하세요, 저는 준이에요. 만나서 반가워요.",hl:true}, {s:"B",en:"Nice to meet you too, Jun.",ko:"저도 반가워요, 준."} ],
  "intro|0|1": [ {s:"A",en:"Hi, I'm Jun.",ko:"안녕하세요, 저는 준이에요."}, {s:"B",en:"Nice to meet you too. I'm Sarah.",ko:"저도 반가워요. 저는 사라예요.",hl:true} ],
  "intro|0|2": [ {s:"A",en:"So you're Jun's coworker?",ko:"준 동료세요?"}, {s:"B",en:"Yes! I've heard a lot about you.",ko:"네! 말씀 많이 들었어요.",hl:true} ],
  "intro|0|3": [ {s:"A",en:"Nice to meet you, Mr. Park.",ko:"만나서 반가워요, 박 선생님."}, {s:"B",en:"Please call me Jun.",ko:"그냥 준이라고 불러주세요.",hl:true} ],
  "intro|0|4": [ {s:"A",en:"How do you two know each other?",ko:"두 분은 어떻게 아는 사이예요?",hl:true}, {s:"B",en:"We went to college together.",ko:"대학을 같이 다녔어요."} ],
  "intro|1|0": [ {s:"A",en:"So, what do you do?",ko:"그래서, 무슨 일 하세요?",hl:true}, {s:"B",en:"I'm a teacher. And you?",ko:"교사예요. 당신은요?"} ],
  "intro|1|1": [ {s:"A",en:"What field are you in?",ko:"어떤 분야에서 일하세요?"}, {s:"B",en:"I work in marketing.",ko:"마케팅 일을 해요.",hl:true} ],
  "intro|1|2": [ {s:"A",en:"What do you do for a living?",ko:"무슨 일 하세요?"}, {s:"B",en:"I'm a software developer.",ko:"저는 소프트웨어 개발자예요.",hl:true} ],
  "intro|1|3": [ {s:"A",en:"Where do you work?",ko:"어디서 일하세요?"}, {s:"B",en:"I work for a small startup.",ko:"작은 스타트업에서 일해요.",hl:true} ],
  "intro|1|4": [ {s:"A",en:"Are you working these days?",ko:"요즘 일하세요?"}, {s:"B",en:"I'm between jobs right now.",ko:"지금은 잠깐 쉬는 중이에요.",hl:true} ],
  "intro|2|0": [ {s:"A",en:"Where are you from?",ko:"어디서 오셨어요?",hl:true}, {s:"B",en:"I'm from Korea. How about you?",ko:"한국에서 왔어요. 당신은요?"} ],
  "intro|2|1": [ {s:"A",en:"Where are you from originally?",ko:"원래 어디 출신이세요?"}, {s:"B",en:"I'm from Seoul, South Korea.",ko:"저는 한국 서울에서 왔어요.",hl:true} ],
  "intro|2|2": [ {s:"A",en:"Are you from Seoul?",ko:"서울 출신이에요?"}, {s:"B",en:"Originally I'm from Busan, but I live in Seoul now.",ko:"원래는 부산 출신인데, 지금은 서울에 살아요.",hl:true} ],
  "intro|2|3": [ {s:"A",en:"Have you ever been to Korea?",ko:"한국에 가본 적 있어요?",hl:true}, {s:"B",en:"Not yet, but I'd love to.",ko:"아직요, 근데 꼭 가보고 싶어요."} ],
  "intro|2|4": [ {s:"A",en:"How long have you lived here?",ko:"여기 산 지는 얼마나 됐어요?",hl:true}, {s:"B",en:"About three years now.",ko:"이제 3년 정도 됐어요."} ],
  "intro|3|0": [ {s:"A",en:"What do you do for fun?",ko:"재미로는 뭐 하세요?",hl:true}, {s:"B",en:"I play guitar on weekends.",ko:"주말에 기타를 쳐요."} ],
  "intro|3|1": [ {s:"A",en:"Any hobbies?",ko:"취미 있어요?"}, {s:"B",en:"I'm really into hiking these days.",ko:"요즘 등산에 푹 빠졌어요.",hl:true} ],
  "intro|3|2": [ {s:"A",en:"How do you spend your free time?",ko:"여가 시간은 어떻게 보내요?"}, {s:"B",en:"I love trying new restaurants.",ko:"새로운 식당 가보는 걸 좋아해요.",hl:true} ],
  "intro|3|3": [ {s:"A",en:"What are your weekends like?",ko:"주말은 보통 어때요?"}, {s:"B",en:"On weekends I usually just relax at home.",ko:"주말엔 보통 집에서 쉬어요.",hl:true} ],
  "intro|3|4": [ {s:"A",en:"I love hiking too!",ko:"저도 등산 좋아해요!"}, {s:"B",en:"We have a lot in common!",ko:"우리 통하는 게 많네요!",hl:true} ],
  "intro|4|0": [ {s:"A",en:"Let's keep in touch.",ko:"연락하고 지내요.",hl:true}, {s:"B",en:"For sure! Here's my number.",ko:"당연하죠! 제 번호예요."} ],
  "intro|4|1": [ {s:"A",en:"Can I get your number?",ko:"연락처 받을 수 있을까요?",hl:true}, {s:"B",en:"Of course, it's 010-1234-5678.",ko:"그럼요, 010-1234-5678이에요."} ],
  "intro|4|2": [ {s:"A",en:"Are you on Instagram?",ko:"인스타 하세요?",hl:true}, {s:"B",en:"Yeah, I'll follow you.",ko:"네, 제가 팔로우할게요."} ],
  "intro|4|3": [ {s:"A",en:"When's the event again?",ko:"그 행사 언제였죠?"}, {s:"B",en:"I'll text you the details.",ko:"자세한 건 문자로 보낼게요.",hl:true} ],
  "intro|4|4": [ {s:"A",en:"I should get going.",ko:"이만 가봐야겠어요."}, {s:"B",en:"It was really nice talking to you.",ko:"얘기 나눠서 정말 좋았어요.",hl:true} ],
  "restaurant|0|0": [ {s:"A",en:"Could I get a latte, please?",ko:"라떼 한 잔 주시겠어요?",hl:true}, {s:"B",en:"Sure. Hot or iced?",ko:"네. 따뜻한 거요, 아이스요?"} ],
  "restaurant|0|1": [ {s:"A",en:"Are you ready to order?",ko:"주문하시겠어요?"}, {s:"B",en:"I'll have the steak, medium rare.",ko:"스테이크 미디엄 레어로 할게요.",hl:true} ],
  "restaurant|0|2": [ {s:"A",en:"Can I get this to go?",ko:"이거 포장되나요?",hl:true}, {s:"B",en:"Of course, I'll pack it up.",ko:"그럼요, 포장해 드릴게요."} ],
  "restaurant|0|3": [ {s:"A",en:"I'll have the curry. And you?",ko:"저는 카레로 할게요. 당신은요?"}, {s:"B",en:"I'll have the same.",ko:"저도 같은 걸로 할게요.",hl:true} ],
  "restaurant|0|4": [ {s:"A",en:"Could we get some water, please?",ko:"물 좀 주시겠어요?",hl:true}, {s:"B",en:"Right away.",ko:"바로 드릴게요."} ],
  "restaurant|1|0": [ {s:"A",en:"What would you recommend?",ko:"뭘 추천하시나요?",hl:true}, {s:"B",en:"The grilled salmon is excellent.",ko:"구운 연어가 아주 좋아요."} ],
  "restaurant|1|1": [ {s:"A",en:"What's your most popular dish?",ko:"가장 인기 있는 메뉴가 뭐예요?",hl:true}, {s:"B",en:"Our seafood pasta, by far.",ko:"단연 해산물 파스타예요."} ],
  "restaurant|1|2": [ {s:"A",en:"Is the pasta good here?",ko:"여기 파스타 맛있어요?",hl:true}, {s:"B",en:"It's one of our best dishes.",ko:"저희 대표 메뉴 중 하나예요."} ],
  "restaurant|1|3": [ {s:"A",en:"What's in this dish?",ko:"이 음식엔 뭐가 들어가나요?",hl:true}, {s:"B",en:"Chicken, peppers, and a cream sauce.",ko:"닭고기, 피망, 크림 소스예요."} ],
  "restaurant|1|4": [ {s:"A",en:"Is this spicy?",ko:"이거 매워요?",hl:true}, {s:"B",en:"A little, but not too much.",ko:"조금요, 그렇게 많이는 아니에요."} ],
  "restaurant|2|0": [ {s:"A",en:"Do you have a table for two?",ko:"두 명 자리 있나요?",hl:true}, {s:"B",en:"Yes, follow me please.",ko:"네, 저를 따라오세요."} ],
  "restaurant|2|1": [ {s:"A",en:"Do you have a reservation?",ko:"예약하셨나요?"}, {s:"B",en:"We have a reservation under Kim.",ko:"Kim 이름으로 예약했어요.",hl:true} ],
  "restaurant|2|2": [ {s:"A",en:"How long is the wait?",ko:"얼마나 기다려야 하나요?",hl:true}, {s:"B",en:"About fifteen minutes.",ko:"15분 정도요."} ],
  "restaurant|2|3": [ {s:"A",en:"Could we sit by the window?",ko:"창가 자리에 앉을 수 있을까요?",hl:true}, {s:"B",en:"Sure, right this way.",ko:"네, 이쪽으로 오세요."} ],
  "restaurant|2|4": [ {s:"A",en:"Is it okay if we sit outside?",ko:"밖에 앉아도 될까요?",hl:true}, {s:"B",en:"Of course, the patio is open.",ko:"그럼요, 테라스 열려 있어요."} ],
  "restaurant|3|0": [ {s:"A",en:"Excuse me, could we get the menu again?",ko:"저기요, 메뉴 다시 볼 수 있을까요?",hl:true}, {s:"B",en:"Certainly, here you go.",ko:"그럼요, 여기 있습니다."} ],
  "restaurant|3|1": [ {s:"A",en:"Could I have some more napkins?",ko:"냅킨 좀 더 주시겠어요?",hl:true}, {s:"B",en:"Of course, one moment.",ko:"그럼요, 잠시만요."} ],
  "restaurant|3|2": [ {s:"A",en:"I think there's a mistake with my order.",ko:"주문이 잘못 나온 것 같아요.",hl:true}, {s:"B",en:"I'm sorry, let me check.",ko:"죄송합니다, 확인해 볼게요."} ],
  "restaurant|3|3": [ {s:"A",en:"This isn't what I ordered.",ko:"이건 제가 주문한 게 아니에요.",hl:true}, {s:"B",en:"My apologies, I'll fix that.",ko:"죄송합니다, 바꿔 드릴게요."} ],
  "restaurant|3|4": [ {s:"A",en:"Could you heat this up a little?",ko:"이거 좀 데워주실 수 있나요?",hl:true}, {s:"B",en:"No problem, I'll be right back.",ko:"네, 금방 가져올게요."} ],
  "restaurant|4|0": [ {s:"A",en:"Can we get the check, please?",ko:"계산서 주시겠어요?",hl:true}, {s:"B",en:"Sure, I'll bring it over.",ko:"네, 가져다드릴게요."} ],
  "restaurant|4|1": [ {s:"A",en:"Do you take cards?",ko:"카드 되나요?",hl:true}, {s:"B",en:"Yes, we accept all major cards.",ko:"네, 주요 카드 다 됩니다."} ],
  "restaurant|4|2": [ {s:"A",en:"Should I pay the whole thing?",ko:"내가 다 낼까?"}, {s:"B",en:"Let's split the bill.",ko:"각자 내자(더치페이 하자).",hl:true} ],
  "restaurant|4|3": [ {s:"A",en:"How much do I owe you?",ko:"나 얼마 내면 돼?"}, {s:"B",en:"It's on me this time.",ko:"이번엔 내가 살게.",hl:true} ],
  "restaurant|4|4": [ {s:"A",en:"Here's twenty. Keep the change.",ko:"여기 20달러요. 잔돈은 가지세요.",hl:true}, {s:"B",en:"Thank you so much!",ko:"정말 감사합니다!"} ],
  "shopping|0|0": [ {s:"A",en:"Do you have this in a medium?",ko:"이거 M 사이즈로 있나요?",hl:true}, {s:"B",en:"Let me check for you.",ko:"확인해 드릴게요."} ],
  "shopping|0|1": [ {s:"A",en:"Do you have this in black?",ko:"이거 검정색으로 있나요?",hl:true}, {s:"B",en:"Yes, it's right over here.",ko:"네, 바로 여기 있어요."} ],
  "shopping|0|2": [ {s:"A",en:"Do you have this in a smaller size?",ko:"이거 더 작은 사이즈 있나요?",hl:true}, {s:"B",en:"We have a small in stock.",ko:"S 사이즈 재고 있어요."} ],
  "shopping|0|3": [ {s:"A",en:"Is this the only color you have?",ko:"색상은 이거 하나뿐인가요?",hl:true}, {s:"B",en:"We also have it in blue.",ko:"파란색도 있어요."} ],
  "shopping|0|4": [ {s:"A",en:"Can I try this on?",ko:"이거 입어봐도 될까요?",hl:true}, {s:"B",en:"Sure, the fitting room is back there.",ko:"그럼요, 탈의실은 저쪽이에요."} ],
  "shopping|1|0": [ {s:"A",en:"Can I help you find anything?",ko:"뭐 찾으시는 거 도와드릴까요?"}, {s:"B",en:"I'm just looking, thanks.",ko:"그냥 구경하는 거예요, 감사해요.",hl:true} ],
  "shopping|1|1": [ {s:"A",en:"Are you looking for something?",ko:"뭐 찾으세요?"}, {s:"B",en:"I'm just browsing for now.",ko:"지금은 그냥 둘러보고 있어요.",hl:true} ],
  "shopping|1|2": [ {s:"A",en:"Let me know if you need anything.",ko:"필요한 거 있으면 말씀하세요."}, {s:"B",en:"I'll let you know if I need help.",ko:"도움 필요하면 말씀드릴게요.",hl:true} ],
  "shopping|1|3": [ {s:"A",en:"Take your time.",ko:"천천히 보세요."}, {s:"B",en:"Actually, could you help me find something?",ko:"사실, 뭐 좀 찾는 거 도와주실래요?",hl:true} ],
  "shopping|1|4": [ {s:"A",en:"What are you shopping for?",ko:"뭐 사러 오셨어요?"}, {s:"B",en:"I'm looking for a gift for my mom.",ko:"엄마 선물을 찾고 있어요.",hl:true} ],
  "shopping|2|0": [ {s:"A",en:"How much is this?",ko:"이거 얼마예요?",hl:true}, {s:"B",en:"That one's twenty-five dollars.",ko:"그건 25달러예요."} ],
  "shopping|2|1": [ {s:"A",en:"Is this on sale?",ko:"이거 할인 중인가요?",hl:true}, {s:"B",en:"Yes, it's 20% off today.",ko:"네, 오늘 20% 할인이에요."} ],
  "shopping|2|2": [ {s:"A",en:"It's ninety dollars.",ko:"90달러예요."}, {s:"B",en:"That's a bit out of my budget.",ko:"이건 제 예산을 좀 넘네요.",hl:true} ],
  "shopping|2|3": [ {s:"A",en:"Can you give me a discount?",ko:"좀 깎아주실 수 있나요?",hl:true}, {s:"B",en:"I can take 10% off.",ko:"10% 정도 빼드릴 수 있어요."} ],
  "shopping|2|4": [ {s:"A",en:"Is there any way to get it cheaper?",ko:"더 싸게 살 방법이 있을까요?",hl:true}, {s:"B",en:"There's a sale next week.",ko:"다음 주에 세일이 있어요."} ],
  "shopping|3|0": [ {s:"A",en:"I'd like to return this, please.",ko:"이거 반품하고 싶어요.",hl:true}, {s:"B",en:"Sure, do you have the receipt?",ko:"네, 영수증 있으세요?"} ],
  "shopping|3|1": [ {s:"A",en:"Can I exchange this for a different size?",ko:"이거 다른 사이즈로 교환할 수 있나요?",hl:true}, {s:"B",en:"Of course, which size?",ko:"그럼요, 어떤 사이즈로요?"} ],
  "shopping|3|2": [ {s:"A",en:"Do you have proof of purchase?",ko:"구매 증빙 있으세요?"}, {s:"B",en:"Here's the receipt.",ko:"여기 영수증이요.",hl:true} ],
  "shopping|3|3": [ {s:"A",en:"What's wrong with it?",ko:"뭐가 문제예요?"}, {s:"B",en:"It doesn't fit.",ko:"사이즈가 안 맞아요.",hl:true} ],
  "shopping|3|4": [ {s:"A",en:"What's your return policy?",ko:"환불 규정이 어떻게 되나요?",hl:true}, {s:"B",en:"Returns within 30 days with a receipt.",ko:"영수증 있으면 30일 이내 반품 가능해요."} ],
  "shopping|4|0": [ {s:"A",en:"How would you like to pay?",ko:"어떻게 결제하시겠어요?"}, {s:"B",en:"I'll pay by card.",ko:"카드로 결제할게요.",hl:true} ],
  "shopping|4|1": [ {s:"A",en:"Can I pay in cash?",ko:"현금으로 내도 되나요?",hl:true}, {s:"B",en:"Of course, no problem.",ko:"그럼요, 문제없어요."} ],
  "shopping|4|2": [ {s:"A",en:"Could I have a bag, please?",ko:"봉투 하나 주시겠어요?",hl:true}, {s:"B",en:"Sure, that's ten cents.",ko:"네, 10센트예요."} ],
  "shopping|4|3": [ {s:"A",en:"Do you have a points card?",ko:"포인트 카드 있으세요?",hl:true}, {s:"B",en:"No, but I'd like to sign up.",ko:"아뇨, 근데 가입하고 싶어요."} ],
  "shopping|4|4": [ {s:"A",en:"Can I get a receipt?",ko:"영수증 받을 수 있을까요?",hl:true}, {s:"B",en:"Here you go. Have a nice day!",ko:"여기요. 좋은 하루 보내세요!"} ],
  "directions|0|0": [ {s:"A",en:"Excuse me, how do I get to the station?",ko:"실례합니다, 역에 어떻게 가나요?",hl:true}, {s:"B",en:"Go straight and it's on your left.",ko:"직진하시면 왼쪽에 있어요."} ],
  "directions|0|1": [ {s:"A",en:"Is this the right way to the museum?",ko:"박물관 가는 길이 이쪽이 맞나요?",hl:true}, {s:"B",en:"Yes, just keep walking.",ko:"네, 계속 걸어가세요."} ],
  "directions|0|2": [ {s:"A",en:"How far is it from here?",ko:"여기서 얼마나 머나요?",hl:true}, {s:"B",en:"About a ten-minute walk.",ko:"걸어서 10분 정도예요."} ],
  "directions|0|3": [ {s:"A",en:"Is it within walking distance?",ko:"걸어갈 수 있는 거리예요?",hl:true}, {s:"B",en:"Yes, it's pretty close.",ko:"네, 꽤 가까워요."} ],
  "directions|0|4": [ {s:"A",en:"Could you show me on the map?",ko:"지도에서 좀 보여주실 수 있나요?",hl:true}, {s:"B",en:"Sure, we're right here.",ko:"네, 우리가 여기 있어요."} ],
  "directions|1|0": [ {s:"A",en:"How do I get to the bank?",ko:"은행에 어떻게 가요?"}, {s:"B",en:"Go straight for two blocks.",ko:"두 블록 직진하세요.",hl:true} ],
  "directions|1|1": [ {s:"A",en:"And then?",ko:"그다음엔요?"}, {s:"B",en:"Turn left at the corner.",ko:"모퉁이에서 왼쪽으로 도세요.",hl:true} ],
  "directions|1|2": [ {s:"A",en:"Where's the entrance?",ko:"입구가 어디예요?"}, {s:"B",en:"It's on your right.",ko:"오른쪽에 있어요.",hl:true} ],
  "directions|1|3": [ {s:"A",en:"Is the café far?",ko:"카페 멀어요?"}, {s:"B",en:"It's just around the corner.",ko:"바로 모퉁이 돌면 있어요.",hl:true} ],
  "directions|1|4": [ {s:"A",en:"Will I be able to find it?",ko:"찾을 수 있을까요?"}, {s:"B",en:"You can't miss it.",ko:"못 찾을 수 없을 거예요.",hl:true} ],
  "directions|2|0": [ {s:"A",en:"Which line goes to downtown?",ko:"시내로 가는 노선이 어느 거예요?",hl:true}, {s:"B",en:"Take the blue line.",ko:"파란색 노선을 타세요."} ],
  "directions|2|1": [ {s:"A",en:"Do I need to transfer?",ko:"환승해야 하나요?",hl:true}, {s:"B",en:"Yes, once at Central Station.",ko:"네, 센트럴역에서 한 번이요."} ],
  "directions|2|2": [ {s:"A",en:"How many stops is it?",ko:"몇 정거장이에요?",hl:true}, {s:"B",en:"Three stops from here.",ko:"여기서 세 정거장이요."} ],
  "directions|2|3": [ {s:"A",en:"Does this bus go to the airport?",ko:"이 버스 공항 가나요?",hl:true}, {s:"B",en:"No, you need the 302.",ko:"아뇨, 302번을 타셔야 해요."} ],
  "directions|2|4": [ {s:"A",en:"Could you tell me when to get off?",ko:"내릴 때 알려주실 수 있나요?",hl:true}, {s:"B",en:"Sure, I'll let you know.",ko:"네, 알려드릴게요."} ],
  "directions|3|0": [ {s:"A",en:"Could you take me to this address?",ko:"이 주소로 가주시겠어요?",hl:true}, {s:"B",en:"Sure, hop in.",ko:"네, 타세요."} ],
  "directions|3|1": [ {s:"A",en:"How much will it be, roughly?",ko:"대략 얼마나 나올까요?",hl:true}, {s:"B",en:"Around fifteen dollars.",ko:"15달러 정도요."} ],
  "directions|3|2": [ {s:"A",en:"Could you turn on the meter?",ko:"미터기 켜주시겠어요?",hl:true}, {s:"B",en:"Of course, sorry about that.",ko:"네, 죄송합니다."} ],
  "directions|3|3": [ {s:"A",en:"I'm in a bit of a hurry.",ko:"제가 좀 급해요.",hl:true}, {s:"B",en:"No problem, I'll take the fast route.",ko:"걱정 마세요, 빠른 길로 갈게요."} ],
  "directions|3|4": [ {s:"A",en:"You can drop me off here.",ko:"여기서 내려주시면 돼요.",hl:true}, {s:"B",en:"Sure, that'll be twelve dollars.",ko:"네, 12달러입니다."} ],
  "travel|0|0": [ {s:"A",en:"I'd like to check in for my flight.",ko:"탑승 수속 하려고요.",hl:true}, {s:"B",en:"May I see your passport?",ko:"여권 좀 보여주시겠어요?"} ],
  "travel|0|1": [ {s:"A",en:"Could I have a window seat?",ko:"창가 자리로 받을 수 있을까요?",hl:true}, {s:"B",en:"Sure, seat 24A.",ko:"네, 24A 자리예요."} ],
  "travel|0|2": [ {s:"A",en:"Any bags to check?",ko:"부치실 짐 있으세요?"}, {s:"B",en:"I have one bag to check in.",ko:"부칠 가방이 하나 있어요.",hl:true} ],
  "travel|0|3": [ {s:"A",en:"Is the flight on time?",ko:"비행기 정시 출발하나요?",hl:true}, {s:"B",en:"Yes, boarding starts at 3.",ko:"네, 3시에 탑승 시작이에요."} ],
  "travel|0|4": [ {s:"A",en:"Which gate does it leave from?",ko:"몇 번 게이트에서 출발하나요?",hl:true}, {s:"B",en:"Gate 22, down the hall.",ko:"22번 게이트, 복도 끝이에요."} ],
  "travel|1|0": [ {s:"A",en:"What's the purpose of your visit?",ko:"방문 목적이 무엇인가요?"}, {s:"B",en:"I'm here on vacation.",ko:"휴가차 왔어요.",hl:true} ],
  "travel|1|1": [ {s:"A",en:"Business or pleasure?",ko:"출장이세요 여행이세요?"}, {s:"B",en:"I'm here for business.",ko:"출장 왔어요.",hl:true} ],
  "travel|1|2": [ {s:"A",en:"How long will you stay?",ko:"얼마나 머무세요?"}, {s:"B",en:"I'll be staying for two weeks.",ko:"2주 동안 머물 거예요.",hl:true} ],
  "travel|1|3": [ {s:"A",en:"Where are you staying?",ko:"어디 묵으세요?"}, {s:"B",en:"I'm staying at a hotel downtown.",ko:"시내 호텔에 머물러요.",hl:true} ],
  "travel|1|4": [ {s:"A",en:"Your documents, please.",ko:"서류 좀 보여주세요."}, {s:"B",en:"Here's my passport.",ko:"여기 여권이요.",hl:true} ],
  "travel|2|0": [ {s:"A",en:"Could you take a picture of us?",ko:"저희 사진 좀 찍어주실 수 있나요?",hl:true}, {s:"B",en:"Sure! Say cheese.",ko:"그럼요! 치즈 하세요."} ],
  "travel|2|1": [ {s:"A",en:"Where's the nearest restroom?",ko:"가장 가까운 화장실이 어디예요?",hl:true}, {s:"B",en:"Just past the gift shop.",ko:"기념품 가게 바로 지나서요."} ],
  "travel|2|2": [ {s:"A",en:"Is there free Wi-Fi here?",ko:"여기 무료 와이파이 있나요?",hl:true}, {s:"B",en:"Yes, the password is on the receipt.",ko:"네, 비밀번호는 영수증에 있어요."} ],
  "travel|2|3": [ {s:"A",en:"What time does it open?",ko:"몇 시에 문 열어요?",hl:true}, {s:"B",en:"At nine in the morning.",ko:"오전 9시에요."} ],
  "travel|2|4": [ {s:"A",en:"Do you know any good places to eat nearby?",ko:"근처에 맛집 아세요?",hl:true}, {s:"B",en:"There's a great noodle shop around the corner.",ko:"모퉁이에 국수집이 맛있어요."} ],
  "travel|3|0": [ {s:"A",en:"I think I lost my passport.",ko:"여권을 잃어버린 것 같아요.",hl:true}, {s:"B",en:"Let's report it right away.",ko:"바로 신고하죠."} ],
  "travel|3|1": [ {s:"A",en:"My luggage didn't arrive.",ko:"제 짐이 안 나왔어요.",hl:true}, {s:"B",en:"I'm sorry. Let's track it.",ko:"죄송합니다. 추적해 볼게요."} ],
  "travel|3|2": [ {s:"A",en:"I missed my connecting flight.",ko:"환승 비행기를 놓쳤어요.",hl:true}, {s:"B",en:"We'll rebook you on the next one.",ko:"다음 편으로 다시 예약해 드릴게요."} ],
  "travel|3|3": [ {s:"A",en:"My flight got delayed.",ko:"제 비행기가 지연됐어요.",hl:true}, {s:"B",en:"How long is the delay?",ko:"얼마나 지연됐어요?"} ],
  "travel|3|4": [ {s:"A",en:"Who should I talk to about this?",ko:"이건 누구한테 말해야 하나요?",hl:true}, {s:"B",en:"The desk over there can help.",ko:"저쪽 데스크에서 도와드릴 거예요."} ],
  "hotel|0|0": [ {s:"A",en:"I have a reservation under Lee.",ko:"Lee 이름으로 예약했어요.",hl:true}, {s:"B",en:"Welcome! Here's your key.",ko:"환영합니다! 여기 열쇠예요."} ],
  "hotel|0|1": [ {s:"A",en:"What time is check-out?",ko:"체크아웃은 몇 시예요?",hl:true}, {s:"B",en:"Check-out is at 11 a.m.",ko:"체크아웃은 오전 11시예요."} ],
  "hotel|0|2": [ {s:"A",en:"Is it possible to check in early?",ko:"일찍 체크인할 수 있을까요?",hl:true}, {s:"B",en:"Let me see if a room is ready.",ko:"준비된 방이 있는지 볼게요."} ],
  "hotel|0|3": [ {s:"A",en:"Could I get a late check-out?",ko:"체크아웃을 늦게 할 수 있을까요?",hl:true}, {s:"B",en:"Sure, until 1 p.m. is fine.",ko:"네, 오후 1시까지 괜찮아요."} ],
  "hotel|0|4": [ {s:"A",en:"Can I leave my luggage here after check-out?",ko:"체크아웃 후에 짐 좀 맡길 수 있나요?",hl:true}, {s:"B",en:"Of course, we'll store it for you.",ko:"그럼요, 보관해 드릴게요."} ],
  "hotel|1|0": [ {s:"A",en:"Could I get some extra towels?",ko:"수건 좀 더 받을 수 있을까요?",hl:true}, {s:"B",en:"Of course, I'll send them up.",ko:"그럼요, 올려 보내드릴게요."} ],
  "hotel|1|1": [ {s:"A",en:"Is breakfast included?",ko:"조식 포함인가요?",hl:true}, {s:"B",en:"Yes, from 7 to 10 a.m.",ko:"네, 오전 7시부터 10시까지예요."} ],
  "hotel|1|2": [ {s:"A",en:"What's the Wi-Fi password?",ko:"와이파이 비밀번호가 뭐예요?",hl:true}, {s:"B",en:"It's 'welcome123'.",ko:"'welcome123'이에요."} ],
  "hotel|1|3": [ {s:"A",en:"Could you call me a taxi?",ko:"택시 좀 불러주시겠어요?",hl:true}, {s:"B",en:"Sure, it'll be here in five minutes.",ko:"네, 5분 안에 올 거예요."} ],
  "hotel|1|4": [ {s:"A",en:"Do you have a room with a better view?",ko:"전망 더 좋은 방 있나요?",hl:true}, {s:"B",en:"We have one facing the ocean.",ko:"바다 쪽으로 난 방이 있어요."} ],
  "hotel|2|0": [ {s:"A",en:"The air conditioning isn't working.",ko:"에어컨이 안 돼요.",hl:true}, {s:"B",en:"I'm sorry, I'll send someone up.",ko:"죄송합니다, 사람을 보내드릴게요."} ],
  "hotel|2|1": [ {s:"A",en:"The room next door is really noisy.",ko:"옆방이 너무 시끄러워요.",hl:true}, {s:"B",en:"I apologize, I'll take care of it.",ko:"죄송합니다, 처리하겠습니다."} ],
  "hotel|2|2": [ {s:"A",en:"There's no hot water.",ko:"온수가 안 나와요.",hl:true}, {s:"B",en:"We'll fix that right away.",ko:"바로 고쳐드릴게요."} ],
  "hotel|2|3": [ {s:"A",en:"Could someone come and take a look?",ko:"누가 와서 봐줄 수 있을까요?",hl:true}, {s:"B",en:"Of course, in just a moment.",ko:"그럼요, 잠시 후에요."} ],
  "hotel|2|4": [ {s:"A",en:"Could I change to another room?",ko:"다른 방으로 바꿀 수 있을까요?",hl:true}, {s:"B",en:"Certainly, let me arrange that.",ko:"물론이죠, 준비해 드릴게요."} ],
  "phone|0|0": [ {s:"A",en:"Hi, this is Jun from ABC Company.",ko:"안녕하세요, ABC사의 준입니다.",hl:true}, {s:"B",en:"Hi Jun, how can I help?",ko:"안녕하세요 준, 무엇을 도와드릴까요?"} ],
  "phone|0|1": [ {s:"A",en:"May I speak to Mr. Smith, please?",ko:"스미스 씨와 통화할 수 있을까요?",hl:true}, {s:"B",en:"One moment, I'll put you through.",ko:"잠시만요, 연결해 드릴게요."} ],
  "phone|0|2": [ {s:"A",en:"I'm calling about the appointment.",ko:"예약 건으로 전화드렸어요.",hl:true}, {s:"B",en:"Sure, what's your name?",ko:"네, 성함이 어떻게 되세요?"} ],
  "phone|0|3": [ {s:"A",en:"Is this a good time to talk?",ko:"지금 통화 괜찮으세요?",hl:true}, {s:"B",en:"Yes, go ahead.",ko:"네, 말씀하세요."} ],
  "phone|0|4": [ {s:"A",en:"Could you put me through to the manager?",ko:"매니저에게 연결해 주시겠어요?",hl:true}, {s:"B",en:"Hold on, please.",ko:"잠시만 기다려 주세요."} ],
  "phone|1|0": [ {s:"A",en:"Hi, is this customer service?",ko:"안녕하세요, 고객센터죠?"}, {s:"B",en:"Speaking. How can I help you?",ko:"전데요. 무엇을 도와드릴까요?",hl:true} ],
  "phone|1|1": [ {s:"A",en:"Can you check my order?",ko:"제 주문 확인해 주실래요?"}, {s:"B",en:"Hold on a second, please.",ko:"잠시만 기다려 주세요.",hl:true} ],
  "phone|1|2": [ {s:"A",en:"Is Mr. Kim there?",ko:"김 씨 계세요?"}, {s:"B",en:"He's not available right now.",ko:"그는 지금 자리에 없어요.",hl:true} ],
  "phone|1|3": [ {s:"A",en:"She's out at the moment.",ko:"그분 지금 외출 중이세요."}, {s:"B",en:"Can I take a message?",ko:"메시지 남겨드릴까요?",hl:true} ],
  "phone|1|4": [ {s:"A",en:"Would you like to leave a message?",ko:"메시지 남기시겠어요?"}, {s:"B",en:"Could you ask her to call me back?",ko:"다시 전화 좀 부탁드린다고 전해주실래요?",hl:true} ],
  "phone|2|0": [ {s:"A",en:"Sorry, you're breaking up.",ko:"죄송한데, 소리가 끊겨요.",hl:true}, {s:"B",en:"Let me move somewhere quieter.",ko:"조용한 데로 옮길게요."} ],
  "phone|2|1": [ {s:"A",en:"Could you speak up a little?",ko:"조금만 더 크게 말씀해 주시겠어요?",hl:true}, {s:"B",en:"Sure, is this better?",ko:"네, 이제 좀 나아요?"} ],
  "phone|2|2": [ {s:"A",en:"I can't hear you very well.",ko:"잘 안 들려요.",hl:true}, {s:"B",en:"Let me call you back.",ko:"제가 다시 걸게요."} ],
  "phone|2|3": [ {s:"A",en:"The signal is bad here.",ko:"여기 신호가 안 좋아."}, {s:"B",en:"Let me call you back.",ko:"제가 다시 걸게요.",hl:true} ],
  "phone|2|4": [ {s:"A",en:"...and that's the plan.",ko:"…그게 계획이에요."}, {s:"B",en:"Could you repeat that?",ko:"다시 한번 말씀해 주시겠어요?",hl:true} ],
  "work|0|0": [ {s:"A",en:"Shall we get started?",ko:"시작할까요?",hl:true}, {s:"B",en:"Yes, let's begin.",ko:"네, 시작하죠."} ],
  "work|0|1": [ {s:"A",en:"We'll launch next month.",ko:"다음 달에 출시할 거예요."}, {s:"B",en:"Just to clarify, do you mean early or late?",ko:"확실히 하자면, 초인가요 말인가요?",hl:true} ],
  "work|0|2": [ {s:"A",en:"...so the budget is set.",ko:"…그래서 예산은 정해졌어요."}, {s:"B",en:"Sorry to interrupt, but I have a question.",ko:"끼어들어 죄송한데, 질문이 있어요.",hl:true} ],
  "work|0|3": [ {s:"A",en:"Did everyone follow that?",ko:"다들 이해되셨어요?"}, {s:"B",en:"Could you go over that again?",ko:"그거 다시 한번 짚어주시겠어요?",hl:true} ],
  "work|0|4": [ {s:"A",en:"What about the budget?",ko:"예산은요?"}, {s:"B",en:"Let's circle back to that later.",ko:"그건 나중에 다시 다루죠.",hl:true} ],
  "work|1|0": [ {s:"A",en:"Which way should we go?",ko:"어느 쪽으로 갈까요?"}, {s:"B",en:"I'd suggest we go with the first option.",ko:"첫 번째 안으로 가는 걸 제안하고 싶어요.",hl:true} ],
  "work|1|1": [ {s:"A",en:"We could save time this way.",ko:"이렇게 하면 시간을 아낄 수 있어요."}, {s:"B",en:"That makes sense to me.",ko:"그거 말 되네요.",hl:true} ],
  "work|1|2": [ {s:"A",en:"Let's just go with my plan.",ko:"그냥 제 안으로 가죠."}, {s:"B",en:"I see your point, but I have concerns.",ko:"무슨 말씀인지 알겠는데, 좀 걱정돼요.",hl:true} ],
  "work|1|3": [ {s:"A",en:"Should we decide now?",ko:"지금 정할까요?"}, {s:"B",en:"Can we look at the numbers first?",ko:"먼저 수치부터 볼 수 있을까요?",hl:true} ],
  "work|1|4": [ {s:"A",en:"What about the new feature?",ko:"새 기능은요?"}, {s:"B",en:"Let's table this for now.",ko:"이건 일단 보류하죠.",hl:true} ],
  "work|2|0": [ {s:"A",en:"Could you give me a hand with this?",ko:"이것 좀 도와줄 수 있어요?",hl:true}, {s:"B",en:"Sure, what do you need?",ko:"그럼요, 뭐가 필요해요?"} ],
  "work|2|1": [ {s:"A",en:"Do you have a minute?",ko:"잠깐 시간 있어요?",hl:true}, {s:"B",en:"Sure, what's up?",ko:"네, 무슨 일이에요?"} ],
  "work|2|2": [ {s:"A",en:"This is a big project.",ko:"이거 큰 프로젝트네요."}, {s:"B",en:"Let me know if you need anything.",ko:"필요한 거 있으면 말해줘요.",hl:true} ],
  "work|2|3": [ {s:"A",en:"Who's handling the report?",ko:"보고서는 누가 맡아요?"}, {s:"B",en:"I'll take care of it.",ko:"제가 처리할게요.",hl:true} ],
  "work|2|4": [ {s:"A",en:"I'm not sure how this works.",ko:"이거 어떻게 하는지 잘 모르겠어요."}, {s:"B",en:"Can you walk me through this?",ko:"이거 차근차근 설명해 줄 수 있어요?",hl:true} ],
  "work|3|0": [ {s:"A",en:"When's the deadline?",ko:"마감이 언제예요?",hl:true}, {s:"B",en:"End of the week.",ko:"이번 주말까지요."} ],
  "work|3|1": [ {s:"A",en:"Can we push the deadline back?",ko:"마감을 좀 미룰 수 있을까요?",hl:true}, {s:"B",en:"Maybe a couple of days.",ko:"이틀 정도는요."} ],
  "work|3|2": [ {s:"A",en:"When can I expect it?",ko:"언제쯤 받을 수 있을까요?"}, {s:"B",en:"I'll get it to you by Friday.",ko:"금요일까지 드릴게요.",hl:true} ],
  "work|3|3": [ {s:"A",en:"How's the project coming along?",ko:"프로젝트 어떻게 돼가요?"}, {s:"B",en:"I'm a little behind on this.",ko:"이거 조금 밀렸어요.",hl:true} ],
  "work|3|4": [ {s:"A",en:"I need the file urgently.",ko:"그 파일 급하게 필요해요."}, {s:"B",en:"Could you send it over ASAP?",ko:"가능한 빨리 보내주실 수 있나요?",hl:true} ],
  "requests|0|0": [ {s:"A",en:"Could you help me for a second?",ko:"잠깐만 도와주실 수 있나요?",hl:true}, {s:"B",en:"Of course, what is it?",ko:"그럼요, 뭔데요?"} ],
  "requests|0|1": [ {s:"A",en:"Would you mind opening the window?",ko:"창문 좀 열어주시겠어요?",hl:true}, {s:"B",en:"Not at all.",ko:"그럼요(전혀요)."} ],
  "requests|0|2": [ {s:"A",en:"Could you do me a favor?",ko:"부탁 하나 들어주실 수 있나요?",hl:true}, {s:"B",en:"Sure, what do you need?",ko:"그럼요, 뭐가 필요해요?"} ],
  "requests|0|3": [ {s:"A",en:"Would it be possible to move our meeting?",ko:"우리 회의를 옮기는 게 가능할까요?",hl:true}, {s:"B",en:"Sure, how about Thursday?",ko:"네, 목요일 어때요?"} ],
  "requests|0|4": [ {s:"A",en:"If it's not too much trouble, could you proofread this?",ko:"번거롭지 않으시면, 이거 검토해 주실 수 있나요?",hl:true}, {s:"B",en:"Happy to. Send it over.",ko:"기꺼이요. 보내주세요."} ],
  "requests|1|0": [ {s:"A",en:"Can I borrow this for a sec?",ko:"이거 잠깐 빌려도 돼요?",hl:true}, {s:"B",en:"Sure, go ahead.",ko:"네, 그러세요."} ],
  "requests|1|1": [ {s:"A",en:"Is it okay if I sit here?",ko:"여기 앉아도 될까요?",hl:true}, {s:"B",en:"Of course, please do.",ko:"그럼요, 앉으세요."} ],
  "requests|1|2": [ {s:"A",en:"Do you mind if I join you?",ko:"같이 껴도 될까요?",hl:true}, {s:"B",en:"Not at all, pull up a chair.",ko:"그럼요, 의자 가져오세요."} ],
  "requests|1|3": [ {s:"A",en:"Would it be alright if I left early?",ko:"일찍 나가도 괜찮을까요?",hl:true}, {s:"B",en:"That's fine, go ahead.",ko:"괜찮아요, 그러세요."} ],
  "requests|1|4": [ {s:"A",en:"May I use your bathroom?",ko:"화장실 좀 써도 될까요?",hl:true}, {s:"B",en:"Sure, it's down the hall.",ko:"네, 복도 끝에 있어요."} ],
  "requests|2|0": [ {s:"A",en:"Why don't we grab some coffee?",ko:"커피 한잔 하는 거 어때요?",hl:true}, {s:"B",en:"Sounds great, let's go.",ko:"좋아요, 가요."} ],
  "requests|2|1": [ {s:"A",en:"How about meeting at seven?",ko:"7시에 만나는 거 어때요?",hl:true}, {s:"B",en:"Seven works for me.",ko:"7시 괜찮아요."} ],
  "requests|2|2": [ {s:"A",en:"I'm getting tired.",ko:"좀 피곤하네요."}, {s:"B",en:"Let's take a break.",ko:"잠깐 쉬어요.",hl:true} ],
  "requests|2|3": [ {s:"A",en:"Where should we eat?",ko:"어디서 먹을까요?"}, {s:"B",en:"We could try the new place.",ko:"새로 생긴 데 가봐도 되고요.",hl:true} ],
  "requests|2|4": [ {s:"A",en:"What do you say we leave now?",ko:"지금 출발하는 거 어때요?",hl:true}, {s:"B",en:"Good idea, let's beat the traffic.",ko:"좋아요, 차 막히기 전에 가요."} ],
  "requests|3|0": [ {s:"A",en:"Could you send me the file?",ko:"파일 좀 보내줄래요?"}, {s:"B",en:"Sure, no problem.",ko:"그럼요, 문제없어요.",hl:true} ],
  "requests|3|1": [ {s:"A",en:"Can you help me tomorrow?",ko:"내일 도와줄 수 있어요?"}, {s:"B",en:"I'd be happy to.",ko:"기꺼이 할게요.",hl:true} ],
  "requests|3|2": [ {s:"A",en:"Want to join us for dinner?",ko:"저녁 같이 먹을래요?"}, {s:"B",en:"I'd love to, but I'm a bit busy.",ko:"그러고 싶은데, 제가 좀 바빠서요.",hl:true} ],
  "requests|3|3": [ {s:"A",en:"Are you free tonight?",ko:"오늘 밤 시간 돼요?"}, {s:"B",en:"Maybe some other time?",ko:"다음 기회에 어때요?",hl:true} ],
  "requests|3|4": [ {s:"A",en:"Will you take the offer?",ko:"그 제안 받을 거예요?"}, {s:"B",en:"Let me think about it.",ko:"좀 생각해 볼게요.",hl:true} ],
  "opinions|0|0": [ {s:"A",en:"What do you think of the plan?",ko:"그 계획 어떻게 생각해요?"}, {s:"B",en:"Personally, I think it's a great idea.",ko:"개인적으로는 좋은 생각인 것 같아요.",hl:true} ],
  "opinions|0|1": [ {s:"A",en:"Should we buy it?",ko:"이거 살까요?"}, {s:"B",en:"If you ask me, it's too expensive.",ko:"제 생각엔 너무 비싸요.",hl:true} ],
  "opinions|0|2": [ {s:"A",en:"What should we do?",ko:"어떻게 해야 할까요?"}, {s:"B",en:"The way I see it, we have two options.",ko:"제가 보기엔 선택지가 둘이에요.",hl:true} ],
  "opinions|0|3": [ {s:"A",en:"Will it work?",ko:"잘 될까요?"}, {s:"B",en:"I'm not sure, to be honest.",ko:"솔직히 잘 모르겠어요.",hl:true} ],
  "opinions|0|4": [ {s:"A",en:"Is it worth it?",ko:"그럴 만한 가치가 있어요?"}, {s:"B",en:"It depends, really.",ko:"사실 경우에 따라 달라요.",hl:true} ],
  "opinions|1|0": [ {s:"A",en:"We should start earlier.",ko:"더 일찍 시작해야 해요."}, {s:"B",en:"I totally agree.",ko:"완전 동의해요.",hl:true} ],
  "opinions|1|1": [ {s:"A",en:"Maybe we need a bigger team.",ko:"팀을 더 키워야 할지도요."}, {s:"B",en:"Exactly, that's what I was thinking.",ko:"맞아요, 저도 그렇게 생각했어요.",hl:true} ],
  "opinions|1|2": [ {s:"A",en:"It might be too risky.",ko:"너무 위험할 수도 있어요."}, {s:"B",en:"You have a point.",ko:"일리 있는 말이에요.",hl:true} ],
  "opinions|1|3": [ {s:"A",en:"We should focus on quality.",ko:"품질에 집중해야 해요."}, {s:"B",en:"I couldn't agree more.",ko:"전적으로 동의해요.",hl:true} ],
  "opinions|1|4": [ {s:"A",en:"It's getting expensive.",ko:"점점 비싸지네요."}, {s:"B",en:"That's true.",ko:"그건 맞아요.",hl:true} ],
  "opinions|2|0": [ {s:"A",en:"Let's just cancel it.",ko:"그냥 취소하죠."}, {s:"B",en:"I see what you mean, but I'm not so sure.",ko:"무슨 말인지 알겠는데, 전 좀 확신이 안 서요.",hl:true} ],
  "opinions|2|1": [ {s:"A",en:"This is clearly the best choice.",ko:"이게 분명 최선이에요."}, {s:"B",en:"I'm afraid I disagree.",ko:"죄송하지만 저는 생각이 달라요.",hl:true} ],
  "opinions|2|2": [ {s:"A",en:"We should cut the budget.",ko:"예산을 줄여야 해요."}, {s:"B",en:"That's one way to look at it, but...",ko:"그렇게 볼 수도 있지만, 다만…",hl:true} ],
  "opinions|2|3": [ {s:"A",en:"Everyone will love it.",ko:"다들 좋아할 거예요."}, {s:"B",en:"I'd have to disagree with that.",ko:"그건 동의하기 어렵네요.",hl:true} ],
  "opinions|2|4": [ {s:"A",en:"I'm sure it'll work.",ko:"분명 될 거예요."}, {s:"B",en:"Have you considered the other side?",ko:"반대편 입장도 생각해 보셨어요?",hl:true} ],
  "emotions|0|0": [ {s:"A",en:"We're going on a trip!",ko:"우리 여행 가!"}, {s:"B",en:"I'm so excited!",ko:"너무 신나요!",hl:true} ],
  "emotions|0|1": [ {s:"A",en:"Any plans for Saturday?",ko:"토요일에 계획 있어?"}, {s:"B",en:"I can't wait for the weekend.",ko:"주말이 너무 기다려져요.",hl:true} ],
  "emotions|0|2": [ {s:"A",en:"I brought you your favorite cake.",ko:"네가 좋아하는 케이크 사 왔어."}, {s:"B",en:"This made my day.",ko:"덕분에 오늘 하루가 행복해요.",hl:true} ],
  "emotions|0|3": [ {s:"A",en:"You got accepted!",ko:"너 합격했대!"}, {s:"B",en:"I'm thrilled about the news.",ko:"그 소식 정말 기뻐요.",hl:true} ],
  "emotions|0|4": [ {s:"A",en:"I fixed your bike for free.",ko:"네 자전거 공짜로 고쳐놨어."}, {s:"B",en:"That's awesome!",ko:"완전 멋지다!",hl:true} ],
  "emotions|1|0": [ {s:"A",en:"I won the lottery.",ko:"나 복권 당첨됐어."}, {s:"B",en:"No way! Really?",ko:"말도 안 돼! 진짜?",hl:true} ],
  "emotions|1|1": [ {s:"A",en:"They're getting married.",ko:"걔네 결혼한대."}, {s:"B",en:"You're kidding!",ko:"농담이지!",hl:true} ],
  "emotions|1|2": [ {s:"A",en:"The store closed down.",ko:"그 가게 문 닫았어."}, {s:"B",en:"I can't believe it.",ko:"믿기지 않아요.",hl:true} ],
  "emotions|1|3": [ {s:"A",en:"He quit his job suddenly.",ko:"걔 갑자기 일 그만뒀어."}, {s:"B",en:"That's so unexpected.",ko:"정말 예상 못 했어요.",hl:true} ],
  "emotions|1|4": [ {s:"A",en:"We're moving to Canada.",ko:"우리 캐나다로 이사 가."}, {s:"B",en:"Wait, what?",ko:"잠깐, 뭐라고?",hl:true} ],
  "emotions|2|0": [ {s:"A",en:"I failed the exam.",ko:"나 시험 떨어졌어."}, {s:"B",en:"I'm so sorry to hear that.",ko:"그 말 들으니 정말 안타까워요.",hl:true} ],
  "emotions|2|1": [ {s:"A",en:"I've been working day and night.",ko:"밤낮으로 일하고 있어."}, {s:"B",en:"That must be really hard.",ko:"정말 힘들겠어요.",hl:true} ],
  "emotions|2|2": [ {s:"A",en:"I don't know how I'll manage.",ko:"어떻게 헤쳐나갈지 모르겠어."}, {s:"B",en:"If you need anything, I'm here.",ko:"필요한 거 있으면 언제든 말해요.",hl:true} ],
  "emotions|2|3": [ {s:"A",en:"I'm not ready to decide.",ko:"아직 결정할 준비가 안 됐어."}, {s:"B",en:"Take all the time you need.",ko:"천천히 시간 가지세요.",hl:true} ],
  "emotions|2|4": [ {s:"A",en:"Everything's going wrong.",ko:"다 엉망이야."}, {s:"B",en:"Things will get better.",ko:"다 나아질 거예요.",hl:true} ],
  "emotions|3|0": [ {s:"A",en:"You okay?",ko:"괜찮아?"}, {s:"B",en:"I'm a little stressed out.",ko:"좀 스트레스 받았어요.",hl:true} ],
  "emotions|3|1": [ {s:"A",en:"The printer jammed again.",ko:"프린터가 또 걸렸어."}, {s:"B",en:"This is so frustrating.",ko:"이거 진짜 답답하네요.",hl:true} ],
  "emotions|3|2": [ {s:"A",en:"The results come out tomorrow.",ko:"내일 결과 나와."}, {s:"B",en:"I'm worried about it.",ko:"그게 좀 걱정돼요.",hl:true} ],
  "emotions|3|3": [ {s:"A",en:"What are you going to do?",ko:"어떻게 할 거야?"}, {s:"B",en:"I don't know what to do.",ko:"어떻게 해야 할지 모르겠어요.",hl:true} ],
  "emotions|3|4": [ {s:"A",en:"You seem down.",ko:"기운 없어 보여."}, {s:"B",en:"It's been a rough week.",ko:"힘든 한 주였어요.",hl:true} ],
  "problems|0|0": [ {s:"A",en:"I'm afraid there's a problem with my order.",ko:"주문에 문제가 좀 있는 것 같아요.",hl:true}, {s:"B",en:"I'm sorry, let me look into it.",ko:"죄송합니다, 알아볼게요."} ],
  "problems|0|1": [ {s:"A",en:"This isn't quite what I expected.",ko:"이건 제가 기대한 것과 좀 달라요.",hl:true}, {s:"B",en:"I understand, let's see what we can do.",ko:"이해해요, 어떻게 할 수 있을지 볼게요."} ],
  "problems|0|2": [ {s:"A",en:"I'd like to speak to a manager.",ko:"매니저와 얘기하고 싶어요.",hl:true}, {s:"B",en:"Of course, one moment.",ko:"그럼요, 잠시만요."} ],
  "problems|0|3": [ {s:"A",en:"I've been waiting for over an hour.",ko:"한 시간 넘게 기다리고 있어요.",hl:true}, {s:"B",en:"I'm very sorry for the delay.",ko:"지연돼서 정말 죄송합니다."} ],
  "problems|0|4": [ {s:"A",en:"Could you look into this for me?",ko:"이 문제 좀 알아봐 주실 수 있나요?",hl:true}, {s:"B",en:"Certainly, I'll check right now.",ko:"그럼요, 지금 확인할게요."} ],
  "problems|1|0": [ {s:"A",en:"I'd like a refund, please.",ko:"환불 부탁드려요.",hl:true}, {s:"B",en:"No problem, I'll process that.",ko:"네, 처리해 드릴게요."} ],
  "problems|1|1": [ {s:"A",en:"This one is broken. Can you replace it?",ko:"이거 고장 났어요. 교체해 주실 수 있나요?",hl:true}, {s:"B",en:"Of course, here's a new one.",ko:"그럼요, 새것 여기요."} ],
  "problems|1|2": [ {s:"A",en:"The app keeps crashing.",ko:"앱이 자꾸 멈춰요."}, {s:"B",en:"How can we fix this?",ko:"이거 어떻게 해결할 수 있을까요?",hl:true} ],
  "problems|1|3": [ {s:"A",en:"The delivery was late again.",ko:"배송이 또 늦었어요."}, {s:"B",en:"What can you do about it?",ko:"이 건에 대해 어떻게 해주실 수 있나요?",hl:true} ],
  "problems|1|4": [ {s:"A",en:"The flight is fully booked.",ko:"항공편이 만석이에요."}, {s:"B",en:"Is there anything you can do?",ko:"해주실 수 있는 게 있을까요?",hl:true} ],
  "problems|2|0": [ {s:"A",en:"You sent the wrong file.",ko:"파일을 잘못 보냈어요."}, {s:"B",en:"I'm really sorry about that.",ko:"그 점 정말 죄송해요.",hl:true} ],
  "problems|2|1": [ {s:"A",en:"The report had errors.",ko:"보고서에 오류가 있었어요."}, {s:"B",en:"That was my fault.",ko:"그건 제 잘못이에요.",hl:true} ],
  "problems|2|2": [ {s:"A",en:"You took my seat.",ko:"제 자리에 앉으셨네요."}, {s:"B",en:"My bad, I didn't realize.",ko:"미안, 몰랐어.",hl:true} ],
  "problems|2|3": [ {s:"A",en:"We got double-charged.",ko:"이중으로 청구됐어요."}, {s:"B",en:"I apologize for the mix-up.",ko:"혼선이 있었던 점 사과드려요.",hl:true} ],
  "problems|2|4": [ {s:"A",en:"Please be more careful next time.",ko:"다음엔 좀 더 조심해 주세요."}, {s:"B",en:"It won't happen again.",ko:"다시는 이런 일 없을 거예요.",hl:true} ],
  "problems|3|0": [ {s:"A",en:"Sorry, I spilled some coffee.",ko:"미안해요, 커피를 좀 흘렸어요."}, {s:"B",en:"No worries, it happens.",ko:"괜찮아요, 그럴 수 있죠.",hl:true} ],
  "problems|3|1": [ {s:"A",en:"I think I was a bit late.",ko:"제가 좀 늦은 것 같아요."}, {s:"B",en:"It's totally fine.",ko:"정말 괜찮아요.",hl:true} ],
  "problems|3|2": [ {s:"A",en:"I broke your mug, sorry.",ko:"네 컵 깼어, 미안해."}, {s:"B",en:"Don't worry about it.",ko:"신경 쓰지 마세요.",hl:true} ],
  "problems|3|3": [ {s:"A",en:"The train was delayed, sorry.",ko:"기차가 지연돼서 미안해요."}, {s:"B",en:"These things happen.",ko:"그런 일도 있는 거죠.",hl:true} ],
  "problems|3|4": [ {s:"A",en:"I'm truly sorry for the mistake.",ko:"실수 정말 죄송해요."}, {s:"B",en:"Apology accepted.",ko:"사과 받아들일게요.",hl:true} ],
  "health|0|0": [ {s:"A",en:"What seems to be the matter?",ko:"어디가 안 좋으세요?"}, {s:"B",en:"I have a headache.",ko:"머리가 아파요.",hl:true} ],
  "health|0|1": [ {s:"A",en:"How long have you felt sick?",ko:"아픈 지 얼마나 됐어요?"}, {s:"B",en:"I've had a fever since yesterday.",ko:"어제부터 열이 나요.",hl:true} ],
  "health|0|2": [ {s:"A",en:"Where does it hurt?",ko:"어디가 아파요?"}, {s:"B",en:"My stomach hurts.",ko:"배가 아파요.",hl:true} ],
  "health|0|3": [ {s:"A",en:"Are you alright?",ko:"괜찮아요?"}, {s:"B",en:"I feel dizzy.",ko:"어지러워요.",hl:true} ],
  "health|0|4": [ {s:"A",en:"You don't look well.",ko:"안 좋아 보여요."}, {s:"B",en:"I think I caught a cold.",ko:"감기에 걸린 것 같아요.",hl:true} ],
  "health|1|0": [ {s:"A",en:"I'd like to see a doctor.",ko:"진료를 받고 싶어요.",hl:true}, {s:"B",en:"Do you have an appointment?",ko:"예약하셨나요?"} ],
  "health|1|1": [ {s:"A",en:"Do I need a prescription for this?",ko:"이거 처방전이 필요한가요?",hl:true}, {s:"B",en:"No, it's available over the counter.",ko:"아뇨, 처방전 없이 살 수 있어요."} ],
  "health|1|2": [ {s:"A",en:"Do you have something for a cough?",ko:"기침에 먹는 약 있나요?",hl:true}, {s:"B",en:"Yes, try this syrup.",ko:"네, 이 시럽을 드셔보세요."} ],
  "health|1|3": [ {s:"A",en:"Any allergies?",ko:"알레르기 있으세요?"}, {s:"B",en:"I'm allergic to penicillin.",ko:"저는 페니실린 알레르기가 있어요.",hl:true} ],
  "health|1|4": [ {s:"A",en:"How often should I take this?",ko:"이거 얼마나 자주 먹어야 하나요?",hl:true}, {s:"B",en:"Twice a day after meals.",ko:"하루 두 번 식후에요."} ],
  "health|2|0": [ {s:"A",en:"Help! Call an ambulance!",ko:"도와주세요! 구급차 불러주세요!",hl:true}, {s:"B",en:"I'm calling now, stay calm!",ko:"지금 전화할게요, 진정하세요!"} ],
  "health|2|1": [ {s:"A",en:"Sir, you can't park here.",ko:"여기 주차 안 됩니다."}, {s:"B",en:"It's an emergency.",ko:"응급 상황이에요.",hl:true} ],
  "health|2|2": [ {s:"A",en:"What happened?",ko:"무슨 일이에요?"}, {s:"B",en:"Someone is hurt.",ko:"누가 다쳤어요.",hl:true} ],
  "health|2|3": [ {s:"A",en:"Where's the nearest hospital?",ko:"가장 가까운 병원이 어디예요?",hl:true}, {s:"B",en:"Two blocks down, on the left.",ko:"두 블록 가서 왼쪽이요."} ],
  "health|2|4": [ {s:"A",en:"I need help right now.",ko:"지금 당장 도움이 필요해요.",hl:true}, {s:"B",en:"Okay, I'm right here.",ko:"네, 제가 바로 옆에 있어요."} ],
  "daily|0|0": [ {s:"A",en:"Are you free this weekend?",ko:"이번 주말에 시간 돼?",hl:true}, {s:"B",en:"I think so, what's up?",ko:"아마? 무슨 일인데?"} ],
  "daily|0|1": [ {s:"A",en:"Wanna grab dinner sometime?",ko:"언제 저녁 같이 먹을래?",hl:true}, {s:"B",en:"Sure, how about Friday?",ko:"좋아, 금요일 어때?"} ],
  "daily|0|2": [ {s:"A",en:"I miss hanging out with you.",ko:"너랑 노는 거 그리워."}, {s:"B",en:"Let's hang out soon.",ko:"조만간 놀자.",hl:true} ],
  "daily|0|3": [ {s:"A",en:"What time works for you?",ko:"넌 몇 시가 괜찮아?",hl:true}, {s:"B",en:"Anytime after six.",ko:"6시 이후면 아무 때나."} ],
  "daily|0|4": [ {s:"A",en:"Movie or dinner?",ko:"영화 볼래 저녁 먹을래?"}, {s:"B",en:"I'm down for whatever.",ko:"난 아무거나 다 좋아.",hl:true} ],
  "daily|1|0": [ {s:"A",en:"I met a celebrity yesterday.",ko:"나 어제 연예인 만났어."}, {s:"B",en:"For real?",ko:"진짜?",hl:true} ],
  "daily|1|1": [ {s:"A",en:"I just got a new job.",ko:"나 새 직장 구했어."}, {s:"B",en:"That's so cool.",ko:"완전 멋지다.",hl:true} ],
  "daily|1|2": [ {s:"A",en:"My flight got cancelled.",ko:"내 비행기 취소됐어."}, {s:"B",en:"Oh, that sucks.",ko:"에이, 별로다(안됐다).",hl:true} ],
  "daily|1|3": [ {s:"A",en:"I'm so tired today.",ko:"나 오늘 너무 피곤해."}, {s:"B",en:"Same here.",ko:"나도 그래.",hl:true} ],
  "daily|1|4": [ {s:"A",en:"This weather is exhausting.",ko:"이 날씨 진짜 지친다."}, {s:"B",en:"Tell me about it.",ko:"내 말이(완전 공감).",hl:true} ],
  "daily|2|0": [ {s:"A",en:"How's everything going with you?",ko:"넌 요즘 다 잘 돼가?",hl:true}, {s:"B",en:"Pretty good, thanks for asking.",ko:"꽤 좋아, 물어봐 줘서 고마워."} ],
  "daily|2|1": [ {s:"A",en:"How's your family doing?",ko:"가족들은 잘 지내?",hl:true}, {s:"B",en:"They're great, thanks.",ko:"다들 잘 지내, 고마워."} ],
  "daily|2|2": [ {s:"A",en:"Anything new with you?",ko:"뭐 새로운 일 있어?",hl:true}, {s:"B",en:"I adopted a puppy!",ko:"나 강아지 입양했어!"} ],
  "daily|2|3": [ {s:"A",en:"This was fun.",ko:"오늘 즐거웠어."}, {s:"B",en:"We should do this more often.",ko:"우리 이거 더 자주 하자.",hl:true} ],
  "daily|2|4": [ {s:"A",en:"It's already December!",ko:"벌써 12월이야!"}, {s:"B",en:"Time flies, huh?",ko:"시간 진짜 빠르다, 그치?",hl:true} ],
  "daily|3|0": [ {s:"A",en:"It's complicated, you know what I mean?",ko:"좀 복잡해, 무슨 말인지 알지?",hl:true}, {s:"B",en:"Yeah, I get it.",ko:"응, 알지."} ],
  "daily|3|1": [ {s:"A",en:"What's the answer?",ko:"답이 뭐야?"}, {s:"B",en:"Let me think...",ko:"음, 생각 좀 해보고…",hl:true} ],
  "daily|3|2": [ {s:"A",en:"Did you like the movie?",ko:"그 영화 좋았어?"}, {s:"B",en:"To be honest...",ko:"솔직히 말하면…",hl:true} ],
  "daily|3|3": [ {s:"A",en:"Are you upset?",ko:"화났어?"}, {s:"B",en:"I mean, it's fine.",ko:"그러니까, 뭐 괜찮아.",hl:true} ],
  "daily|3|4": [ {s:"A",en:"...sorry, I got distracted.",ko:"…미안, 딴 데 정신 팔렸어."}, {s:"B",en:"Anyway, where were we?",ko:"아무튼, 우리 어디까지 얘기했지?",hl:true} ]
};
